### ISSUE TITLE
Possible to have different DragAdornerTemplates based on DropTarget?

### ISSUE THREAD

**Issue by t2test** [punker76/gong-wpf-dragdrop#115]
A Question: is it possible to change the DragAdornerTemplate on the fly depending on the DropTarget thats under the Mousepointer?  

Thanks!

**Comment by Schnjan** [comment]
It would be great if the DragAdornerTemplate could be set on the target element, since this element knows how it's going to process the dragged data and can display a matching preview on the cursor.
