### ISSUE TITLE
Adorner on other types of control

### ISSUE THREAD

**Issue by JobaDiniz** [punker76/gong-wpf-dragdrop#121]
Hi, awesome project.
I'm using to drop files onto a UserControl, which is inside a Window. However, there are 2 issues for me:
1. When you drag a file into a place that can be dropped, the default behavior of most applications is to show the file icon. When I drag a file using this library, the file icon does not show.
2. The adorner is not shown. It seems there isn't adorners for Window, TextBox or UserControls. I'd like to show some fancy clue to user that the drop can be done.

**Comment by punker76** [comment]
@JobaDiniz Yes there is no default for this and I will not add this. But it's possible with the current set of interfaces and properties. Take a look at the sample. The issue #85 demonstrates this for a TextBox. Hope this is ok for you. thx

![image](https://cloud.githubusercontent.com/assets/658431/22039006/c6a3bedc-dcfd-11e6-9e97-08d5f537f1ca.png)

**Comment by JobaDiniz** [comment]
Sorry, I did not quite understand.
Regarding _issue 1_, is there something that I can do? Some api that I can plug into in order to show the file icon? (I've already have a code to create an image given the file extension).

About _issue 2_, if I understood right, I should create a [class](https://github.com/punker76/gong-wpf-dragdrop/commit/939d79607a34dc6e64fe2082046df4a144abbebb#diff-3fb96dd8ead6076127c3ad62da161ed1R24) that inherits from `DropTargetAdorner`, is that it?
