### ISSUE TITLE
FlowDocument in ItemTemplate

### ISSUE THREAD

**Issue by hawelo** [punker76/gong-wpf-dragdrop#123]
Hi,
I have a special case where I need to display flowdocuments in an itemscontrol and to support ordering of these flowdocuments by drag&drop. It looks that this special case is not currenlty supported.
Is there a way to make this work with the gong drag&drop?
Here is an example of ItemTemplate:
```
<DataTemplate>
    <FlowDocumentScrollViewer IsSelectionEnabled="False">
        <FlowDocument>
            <Paragraph>Test</Paragraph>
        </FlowDocument>
    </FlowDocumentScrollViewer>
</DataTemplate>
```

**Comment by punker76** [comment]
@hawelo try setting `IsHitTestVisible="False"` (i tested it shortly and it seems to work, i added it to the default example)

```xaml
<DataTemplate>
  <FlowDocumentScrollViewer IsSelectionEnabled="False" IsHitTestVisible="False">
    <FlowDocument>
      <Paragraph>Test</Paragraph>
    </FlowDocument>
  </FlowDocumentScrollViewer>
</DataTemplate>
```
