### ISSUE TITLE
Nested DragDrop ItemControls

### ISSUE THREAD

**Issue by brianke** [punker76/gong-wpf-dragdrop#133]
I have a scenario where I have an ItemsControl (Invoicesitems) within and ItemsControl (Invoice), each implementing the drag/drop functionality.  I have added IDropTarget.DragOVer & IDropTarget.Drop to each view model.

When I drag InvoiceItems above or below the boundaries of its ItemsControl (within a group box), I will see a drag indicator display between the Invoices.

Is there a way to limit where the drag indicator displays or change its appearance (i.e., circle with slash) when outside a certain boundary (i.e., the ItemsControl list or a GroupBox)?

**Comment by punker76** [comment]
@brianke You can inherit from `DropTargetAdorner` and implement your own adorner and set the type at the IDropTarget implementation.

```csharp
public class CustomDropTarget : IDropTarget
{
  public void DragOver(IDropInfo dropInfo)
  {
    dropInfo.Effects = DragDropEffects.Copy;
    dropInfo.DropTargetAdorner = typeof(CustomDropTargetAdorner);
  }

  public void Drop(IDropInfo dropInfo)
  {
  }
}
```
