### ISSUE TITLE
NullReferenceException on Drag to not yet set collection

### ISSUE THREAD

**Issue by byggwir** [punker76/gong-wpf-dragdrop#134]
I have 2 ListBoxes both bound to an ObservableCollection of the 2 viewmodels in 2 separate controls of the same window.
The source listbox is filled with items.
To explain I will give all involved objects a name (dataItem, chart, displayableDataItems) as the setup is a bit complicated. What makes this bug difficult for me is that it is impossible to catch the exception and ignore it !

In my example I want to display a "dataItem" (Source for DD) in one of several available charts. A chart can display several data items and therefore has a list of displayableDataItems (Target DD) in its viewModel. A sketch of my UI:

    (bound to                   (bound to viewmodel with list of charts
    viewmodel                   
    with list                        displayableItemsList is a property of charts
    of displayItems)            and bound as Itemssource to the list)
    -----------------          -------------------------------------------------------------
    |displayItem1 |         | Chart 1                                                       |
    |displayItem2 |         | Chart 2                                                       |
    -----------------       |                     displayableItems of selected Chart        |
    (drag -->)              |                    | (empty if no chart selected)           | |
                              --------------------------------------------------------

Now if a user wants to assign a dataItem to a chart he has to select the chart from a list and a control populates the displayableDataItems list. So if the user has not selected a chart this list is empty. Everything via WPF binding.
Now the user can drag drop a dataItem to the displayableDataItems to add it there.
So the working workflow is:
User --> select Chart
list displayableDataItems gets populated
User --> drag drop dataItem --> Chart.displayableDataItems
Success

not working:
User does NOT select a chart
--> list displayableDataItems is not bound to an existing ObservableCollection
User --> drag drop dataItem --> not existing Chart.displayableDataItems

==> NullReferenceException (DefaultDropHandler.cs line 94 version:07 May 2015)
This bug also exists in version 1.4.0.1

**Comment by punker76** [comment]
@byggwir can you maybe simplify this example, so it's easier to understand what happen and easier to debug. thx!

**Comment by byggwir** [comment]
Sorry. Overlooked the question. I have to see if I can get a working sample.

**Comment by punker76** [comment]
@byggwir thx
