### ISSUE TITLE
Dropping outside of window

### ISSUE THREAD

**Issue by PassivePicasso** [punker76/gong-wpf-dragdrop#136]
There doesn't appear to be a way to handle dropping items outside a window, whether to the desktop or otherwise.
Falling back on the default windows drag and drop features you should be able to provide the serialization information needed in the ViewModel that implements the IDragSource.

Additionally it should be possible to get a Dropped message when an item is dropped outside a window. this doesn't appear to be available either.

If I'm wrong please let me know, and perhaps mark this issue for documentation updates.

**Comment by parapsychopatolog** [comment]
I need this feature too.

**Comment by teekay** [comment]
I'm also interested in getting this working - I want my app to behave well with others, and to enable dragging and dropping items (which are music files) from my apps to other players and/or onto a folder in Explorer.

Happy to offer a hand if this is doable, just need a little direction.

**Comment by klingni** [comment]
Dropping outside the window would be very nice.

**Comment by omnjpa27516** [comment]
This pull solves the situation of dragging data from app to app, but how to solve the problem from app to explorer?
@punker76
