### ISSUE TITLE
Incorrect positions on ListView with applied filter

### ISSUE THREAD

**Issue by DominikPalo** [punker76/gong-wpf-dragdrop#140]
When I'm using filtering in ListView (so some items are hidden), drag & drop functionality doesn't work as expected: dropped items are placed on incorrect position (it seems that dropInfo.InsertIndex points to position in currently rendered list of items, but item is placed using this index to original, non-filtered list of items, so it's is offseted by hidden items)

**Comment by punker76** [comment]
@DominikPalo this should already fixed in the alpha version, there is also a new property `UnfilteredInsertIndex` at the DropInfo.

**Comment by DominikPalo** [comment]
Thanks, I've updated the library to the latest alpha version and now it works OK :+1:
