### ISSUE TITLE
Example when using C# Code to build control

### ISSUE THREAD

**Issue by ZionGates** [punker76/gong-wpf-dragdrop#147]
Greetings Gurus,
Can an example be provided that assigns drag and drop functionality using c# code to build the button instead of XAML exclusive examples
Like; Button but = new Button();
..................
...................

thanks

**Comment by punker76** [comment]
@ZionGates What example exactly do you need? What do you mean with "build the button" ?

**Comment by SuicSoft** [comment]
@punker76 @ZionGates means to not use any XAML
