### ISSUE TITLE
Add ability to use a custom xaml for the drag tooltips

### ISSUE THREAD

**Issue by SuicSoft** [punker76/gong-wpf-dragdrop#149]
Hi,
So the reason for this is so that we can have tooltip styles such as Metro or Material Design which could be animated

**Comment by punker76** [comment]
What do you mean with tooltips? It is already possible to have custom a ‘DragAdorner‘.

**Comment by SuicSoft** [comment]
@punker76 I mean custom xaml for the tooltip when dragging. WIll ```DragAdorner``` work here

**Comment by punker76** [comment]
that's the work of the adorner

**Comment by SuicSoft** [comment]
Ok, thanks anyways
