### ISSUE TITLE
Stop scrolling when dropping not allowed

### ISSUE THREAD

**Issue by Sayyid-A** [punker76/gong-wpf-dragdrop#154]
Hello,

First off, thank you for such great framework. It works really like a charm, one issue thought.
I set a DataGrid as follows:

```
EnableRowVirtualization="True"
EnableColumnVirtualization="True"
VirtualizingStackPanel.IsVirtualizing="True"
VirtualizingStackPanel.VirtualizationMode="Recycling"
ScrollViewer.IsDeferredScrollingEnabled="True"
ScrollViewer.HorizontalScrollBarVisibility="Auto"
dd:DragDrop.IsDragSource="True"
dd:DragDrop.IsDropTarget="True"
dd:DragDrop.UseDefaultDragAdorner="False"
dd:DragDrop.UseDefaultEffectDataTemplate="False"    
dd:DragDrop.EffectMoveAdornerTemplate="{StaticResource EffectMoveAdorner}"          
dd:DragDrop.EffectCopyAdornerTemplate="{StaticResource EffectCopyAdorner}"          
dd:DragDrop.EffectNoneAdornerTemplate="{StaticResource EffectNoneAdorner}"          
dd:DragDrop.DropHandler="{Binding}"
```

```
public void DragOver(IDropInfo dropInfo)
{
  if (!condition)
    dropInfo.Effects = DragDropEffects.None;        
}
```

So it is only allowed to drop items into another lists, but not to rearrange in the DataGrid.
It works fine, but the DataGrid keeps scrolling horizontally/vertically while dragging items!

I tried many workarounds with no luck, is it possible to stop that scrolling while dragging?

**Comment by punker76** [comment]
@Sayyid-A With v1.1.0 comes a new attached property `DropScrollingMode` to set the scrolling for the target. I added also the property `TargetScrollingMode` to the `DropInfo` to allow override the scrolling on the fly.
