### ISSUE TITLE
Most simplest case is not working

### ISSUE THREAD

**Issue by AkilaeTribe** [punker76/gong-wpf-dragdrop#156]
In a new project, when you declare a Rectangle and add the attached properties DragDrop.IsDragSource="True" and DragDrop.DragHandler="{Binding}" (with DataContext implementing IDragSource), method IDragSource.StartDrag(IDragInfo dragInfo) is never called.

The fact is that the DragDrop.DragSource_PreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e) method returns early, in the first and big 'if' test, because the method HitTestUtilities.IsNotPartOfSender(object sender, MouseButtonEventArgs e) returns true.

**Comment by MarkusPalcer** [comment]
Hi,

I just tried to recreate your issue out of curiousity and found that the following code makes it work:

        `<ItemsControl
            dragDrop:DragDrop.IsDropTarget="True"
            dragDrop:DragDrop.IsDragSource="True"
            dragDrop:DragDrop.UseDefaultDragAdorner="True"
            dragDrop:DragDrop.DefaultDragAdornerOpacity="0.3"
            dragDrop:DragDrop.DropHandler="{Binding}"
            Background="Transparent"
            >
            <ItemsControl.ItemTemplate>
                <DataTemplate DataType="local:ItemViewModel">
                    <Rectangle Margin="0,0,0,10"
                               Fill="Red" Height="10">

                    </Rectangle>
                </DataTemplate>
            </ItemsControl.ItemTemplate>
            <local:ItemViewModel Index="0" />
            <local:ItemViewModel Index="1" />
            <local:ItemViewModel Index="2" />
        </ItemsControl>`

**Comment by pinki** [comment]
Hi,
I just noticed that `m_DragInfo.VisualSourceItem` can't be `null`.

In my project, I want to create a new Object to drag everytime I start dragging.
`VisualSource` is a simple `Grid` that is marked as drag source and that has a drag handler.
This worked for me in ALPHA013, but not in ALPHA017.

Why does the VisualSourceItem has to be set?

**Comment by punker76** [comment]
@pinki Can you provide a short sample? Thx!

**Comment by pinki** [comment]
Sure!

[DragDropFailTest.zip](https://github.com/punker76/gong-wpf-dragdrop/files/432673/DragDropFailTest.zip)

**Comment by punker76** [comment]
@pinki @MarkusPalcer @AkilaeTribe The most simplest case should now work ;-) I made some changes to allow drag elements which are not ItemControls, all available in upcoming v1.1.0
@pinki Thx for the sample!

**Comment by pinki** [comment]
Thanks for fixing :)
