### ISSUE TITLE
Question about persistance after drop

### ISSUE THREAD

**Issue by voidray** [punker76/gong-wpf-dragdrop#160]
The example on the github page explains the parent/child drag&drop scenario.
What if I just want to drag items between multiple lists that are bound to the same collection?
In the Drop-method I only seem to have access to the the target-collection (not the object that contains the list). What I need to know is the Parent-ID of the record that contains the collection in order to set the foreign key for the dropped item?

Data structure is basically as follows:
KanbanList
  - Id
  - Name
  - List<Note>
Note
  - Id
  - Name
  - KanbanListId

In the WPF View there is a ItemsControl that displayes all the KanbanList and in each KanbanList there is a ListBox that binds to the Notes belonging to that list.

**Comment by punker76** [comment]
@voidray I think that maybe the default drop handler can not check such complex scenario. But you can do this by implementing the `IDropTarget` and handle this stuff by yourself.
