### ISSUE TITLE
Checkbox in nested grid view (both w/ drag-n-drop) requires double click

### ISSUE THREAD

**Issue by ArcadeRenegade** [punker76/gong-wpf-dragdrop#166]
Small issue. First thanks for this library it really simplifies things so I didn't have to write a while bunch of code for drag and drop. 

I have a DataGrid that has drag-n-drop. That works fine. For each row in this data grid, there are row details that show when the row is selected. 

In the row details, there is a ListView with a grid. This ListView also has drag-n-drop. The drag-n-drop functionality works fine for both, but enabling drag-n-drop for the ListView prevents interaction with a check box in a column on first click. Seems like it is registering it as a drag operation rather than a check the checkbox operation. The workaround is to quickly double click the checkbox to check or uncheck it. 

Hope that's not too confusing. I'll try and post a screenshot when I can.

**Comment by punker76** [comment]
@ArcadeRenegade Is it maybe possible that you create a small application with some dummy data, so i can debug and find a solution? maybe its related to the checkbox colum (only a thought).

**Comment by ArcadeRenegade** [comment]
Here is a screenshot:

![image](https://cloud.githubusercontent.com/assets/13874898/13090032/62584398-d4a8-11e5-980b-8141125a16b2.png)

If it's not too much trouble, I think it would be easiest for you to clone my repo. All dependancies are NuGet packages except for OpenHardwareMonitor which you can [download here](http://openhardwaremonitor.org/).

https://github.com/ArcadeRenegade/SidebarDiagnostics

**Comment by punker76** [comment]
@ArcadeRenegade can i compile and run this under win 7?

**Comment by ArcadeRenegade** [comment]
Yessir

**Comment by punker76** [comment]
@ArcadeRenegade It would be nice if you can test the latest source (pre-release). I changed a little bit with nested ItemsControls. Thx!

**Comment by ArcadeRenegade** [comment]
It works now! Thanks @punker76!
