### ISSUE TITLE
ListBox.Drop Event fired before item added to target list

### ISSUE THREAD

**Issue by smismismi** [punker76/gong-wpf-dragdrop#170]
Hello,

i wanna validate (and if applicable highlight the ffected items) but:
When i listen to the "Drop" event on a ListBox, the dropped item is not (yet) added to target list at the moment the drop event is fired. 

Is this the right behavior? If it is, where to hook for a validation?

Thanks,
smi

**Comment by punker76** [comment]
@smismismi You should better use and implement the `IDropTarget` interface to validate effected items. You can validate with the `void DragOver(IDropInfo dropInfo);` method.
