### ISSUE TITLE
Do not use Application.Current.MainWindow

### ISSUE THREAD

**Issue by FrecherxDachs** [punker76/gong-wpf-dragdrop#171]
DragDrop.CreateDragAdorner uses Application.Current.MainWindow if the current element is not hosted directly in a window. Never ever try to guess the correct window by such APIs, this will fail everytime, please simply remove this and return null.

**Comment by FrecherxDachs** [comment]
I think this issue goes hand in hand with #165

**Comment by punker76** [comment]
@FrecherxDachs changed with 0f56678d38536b9962d55f3002136c054573bcb7
