### ISSUE TITLE
Don't allow to add childs to DateTemplate in TreeView

### ISSUE THREAD

**Issue by DominikPalo** [punker76/gong-wpf-dragdrop#175]
I'm using TreeView with drag&drop functionality in my app with different `HierarchicalDataTemplates` for different levels. But for end nodes I'm using `DataTemplates` and I don't want to allow drop childs into these templates. But when I set `AllowDrop` to `false` for root elements in these `DataTemplates`, dropping ti these nodes doesn't work (as expected), but I can't also reorder them. It is possible to don't allow to add child into these end nodes but still allow to reorder them?

**Comment by punker76** [comment]
@DominikPalo I think using the `DragDropContext` property is the right part for your problem https://github.com/punker76/gong-wpf-dragdrop/blob/master/GongSolutions.Wpf.DragDrop/DragDrop.cs#L255-L256
