### ISSUE TITLE
Enabling drag drop for multi-select tree view

### ISSUE THREAD

**Issue by deejay220989** [punker76/gong-wpf-dragdrop#178]
Hi,

I have a multi-select tree view control, and I'm wondering how can I enable to drag drop multiple items from a tree view.

Is it possible?

Thanks!

**Comment by punker76** [comment]
@deejay220989 You can implement the `IDragSource` and `IDropTarget` interfaces where you can put the selected items in and handle it on the drop site. Hope this helps.
