### ISSUE TITLE
How to give the dragged-over control a chance to react to the drag in progress?

### ISSUE THREAD

**Issue by Haukinger** [punker76/gong-wpf-dragdrop#183]
I'm using the eyeshot 3d viewport (derives from Image, if that matters), and I want to drag stuff from the part library into the 3d viewport.
My problem's that I don't get move movement or give feedback events. I have to update the position of a temporary version of the new 3d object while the user moves the mouse, performing snapping and so on, what's the best way to achieve this? Can I use a "fake adorner" that forwards events to the actual viewport or can i extend IDropHandler with a method that's called regularly while the mouse is above the drop target?

**Comment by punker76** [comment]
@Haukinger Can you create a sample with this scenario? Thx

**Comment by Haukinger** [comment]
I did it through a new attached property `ManualItemHandling` that (if set to `true`) prevents aborting the drag-drop-operation if no `VisualSourceItem` could be found.

See [this branch in my fork](https://github.com/Haukinger/gong-wpf-dragdrop/tree/itemless)...

**Comment by Haukinger** [comment]
Any news here? It would be really cool if you could integrate dragging onto controls that are no items control, e.g. a canvas.
