### ISSUE TITLE
Next item gets dragged when starting dragging in lower half of item

### ISSUE THREAD

**Issue by MarkusPalcer** [punker76/gong-wpf-dragdrop#188]
I want the user to be able to drag Items in an ItemsControl.
My Items consist of a GroupBox which contains a ComboBox and a Button.
When I start dragging an Item from its upper half, the item itself starts getting dragged.
When I however start the dragging from the lower half, the next item gets dragged (the ghostly adorner shows the next item and the index that the drop handler gets is also wrong).

I created a minimal sample and a video showing the effect. The sources of the sample as well as the video are attached.
In the minimal sample the drop handler doesn't do anything, so no actual reordering takes place, but that could easily be added.

This version uses the sources of the Alpha 13, but the effect also happens with the latest non-prerelease version.

[WpfApplication2.zip](https://github.com/punker76/gong-wpf-dragdrop/files/331888/WpfApplication2.zip)
[sample video.zip](https://github.com/punker76/gong-wpf-dragdrop/files/331889/sample.video.zip)

**Comment by punker76** [comment]
@MarkusPalcer Thx for the sample and the video!

**Comment by MarkusPalcer** [comment]
Thx for the fix
