### ISSUE TITLE
DragAdornerTemplate for Files

### ISSUE THREAD

**Issue by MoiraG** [punker76/gong-wpf-dragdrop#189]
Hello,

is it possible to change the DragAdornerTemplate for dropping files into the view?
I have used the DataTemplate "DragAdorner" from the example. It works great for items in a Listbox but not for files. Am I doing something wrong, or is it not possible?

Thanks and best regards

**Comment by punker76** [comment]
-> todo https://github.com/punker76/gong-wpf-dragdrop/issues/229
