### ISSUE TITLE
DragAdoner issue

### ISSUE THREAD

**Issue by sanket-pattekar** [punker76/gong-wpf-dragdrop#190]
Hi

We have a issue with DragAdoner when the IsDropTarget is false.

To explain this further, we have a DragAdoner that we use when a list item is dragged. 
For the ListControl1, we have set the IsDragSource=true and IsDropTarget=false (We want the list to act as a source  but not the target). 
For the ListControl2, we have set the IsDragSource=false and IsDropTarget=true (We want the list to act as a target but not as a source).

The issue is that when we drag any item from ListControl1, then there is no adoner shown. However when this item is dragged on ListControl2 we see the adoner. The requirement is that we need the adoner all the time (on ListControl1 and ListControl2 ). Also we need the adoner always (as WIndows Explorer) even in case where the item cannot be dropped.

~Sanket

**Comment by punker76** [comment]
@sanket-pattekar I've added a sample to the demo to show this behavior with this custom DropHandler until a better solution is available. Set the `IsDropTarget` to true and implement your own drop handler and set it to `DropHandler`. You can take a look to the samples at the issues tab #58.

```csharp
  public class ListBoxCustomDropHandler : DefaultDropHandler
  {
    public override void DragOver(IDropInfo dropInfo)
    {
      if (dropInfo.VisualTarget == dropInfo.DragInfo.VisualSource)
      {
        dropInfo.NotHandled = dropInfo.VisualTarget == dropInfo.DragInfo.VisualSource;
      }
      else
      {
        base.DragOver(dropInfo);
      }
    }

    public override void Drop(IDropInfo dropInfo)
    {
      if (dropInfo.VisualTarget == dropInfo.DragInfo.VisualSource)
      {
        dropInfo.NotHandled = dropInfo.VisualTarget == dropInfo.DragInfo.VisualSource;
      }
      else
      {
        base.Drop(dropInfo);
      }
    }
  }
```

Hope this is ok for you.

**Comment by ShemJM** [comment]
@punker76 This works fine for showing the adorner over the source list, but I think the desired effect is to show it everywhere. Even over controls that are not drop targets, Do you know a way to do that?
