### ISSUE TITLE
Release mode key issue

### ISSUE THREAD

**Issue by jeffkingdev** [punker76/gong-wpf-dragdrop#195]
Hi,

I am trying to build your library in release mode and it's saying I can't because of the gong-wpf-dragdrop.pfx.  How can I use this in release mode?

I get "
Severity	Code	Description	Project	File	Line	Suppression State
Error		Cannot import the following key file: gong-wpf-dragdrop.pfx. The key file may be password protected. To correct this, try to import the certificate again or manually install the certificate to the Strong Name CSP with the following key container name: VS_KEY_XXXXXXXXXXXX	GongSolutions.Wpf.DragDrop (NET4)"

Thanks

**Comment by punker76** [comment]
@jeffkingdev This is for the release only, cause many people need strong named dlls (I really hate this). Use this [Strong Namer](https://github.com/dsplaisted/strongnamer) library and remove the pfx from the release build if you need a self compiled release. I will remove this on v1.0 cause nobody needs strong named dlls!!
