### ISSUE TITLE
Shortcut for copy-paste / cut-paste functionality?

### ISSUE THREAD

**Issue by jack-fraser** [punker76/gong-wpf-dragdrop#200]
It would be cool if there was an option that was something like:

```
dd:DragDrop.dragMode="copy"
dd:DragDrop.dragMode="cut"
```

So that the original selection could be either removed or kept without having to write up your own binding :+1:

**Comment by punker76** [comment]
@jack-fraser Such configuration is now possible via `DragDropCopyKeyState` attached property. It's available via pre-release and upcoming v1.0

**Comment by 4ipalino** [comment]
I tried this copy feature, but it´s not working as expected.
If i use:
                      dragDrop:DragDrop.DragDropCopyKeyState="ControlKey"
it creates a copy on drop, when Ctrl is pressed otherwise not -> as expected.

If i use:
                      dragDrop:DragDrop.DragDropCopyKeyState="LeftMouseButton"
it never creates a copy. I wanted always a copy on drop. Is this possible?

**Comment by punker76** [comment]
@4ipalino Hi, I found out, that the drop event doesn't give us the right keystates. So I will fix this very soon.
