### ISSUE TITLE
Default behavior example shows wrong mouse cursor during drag

### ISSUE THREAD

**Issue by rillig** [punker76/gong-wpf-dragdrop#201]
Using version 0.1.4.3, I have followed the instructions in the `README.md` for the simple example.

* started a new project in Visual Studio 2015
* added the namespace to the XAML
* added a `ListBox`
* added the DragDrop properties
* populated the list items with simple strings

When I run this example, I can drag and drop the items in the list, which, by the way, is as simple as it could get. Many thanks for doing all the work in the background.

But the mouse cursor shows a Copy operation, even though I am just reordering the items in the list. It should show a Move operation instead. On the other hand, when I have two list boxes, the Copy operation is correct, since the items are really copied.

**Comment by punker76** [comment]
@rillig The default drag and drop action is now to move items. This behavior can be changed by `DragDropCopyKeyState` attached property, available in pre-release and upcoming v1.0

**Comment by rillig** [comment]
Cool, just upgrading to 1.0.0-ALPHA017 fixed this beautifully. Thank you very much.
