### ISSUE TITLE
Prevent scrolling in 1 direction

### ISSUE THREAD

**Issue by osicka** [punker76/gong-wpf-dragdrop#205]
Dragging to a list box where there are items wider than the list box sees the list box scroll horizontally as the cursor passes the list box boundary. This is undesired behaviour as most of the information scrolls away leaving only the tail of the larger items showing.

![image](https://cloud.githubusercontent.com/assets/4978919/18237800/28f265e6-7379-11e6-8275-33188e21b157.png)

Is there a way to prevent scrolling in a certain direction while dragging?

Scrolling vertically in this instance is fine as the user may want to do that when the list box contains many items.

**Comment by punker76** [comment]
@osicka I planed to make the scrolling behavior better (e.g. adding new attached properties) for v1.1.0

**Comment by punker76** [comment]
@osicka With v1.1.0 comes a new attached property `DropScrollingMode` with this enum values

```
  /// <summary>
  /// Specifies how <see cref="T:System.Windows.Controls.ScrollViewer" /> reacts to drop operation.
  /// </summary>
  public enum ScrollingMode
  {
    None,
    HorizontalOnly,
    VerticalOnly,
    Both
  }
```
