### ISSUE TITLE
Drop Target Adorner Z level

### ISSUE THREAD

**Issue by osicka** [punker76/gong-wpf-dragdrop#207]
I am dropping onto a Button after setting the DropTargetAdorner to DropTargetAdorners.Highlight. The highlight for the button appears above the text for the dragged information. See below.

![image](https://cloud.githubusercontent.com/assets/4978919/18239312/d4a5468e-7387-11e6-80b5-8bf6d2cc5f9e.png)

**Comment by punker76** [comment]
@osicka Sorry for the delay! I cannot reproduce this. I tried DragAdornerTemplate and different tests with an ItemTemplate for ListBox. Can you create a short sample to demonstrate this issue? Thx!
