### ISSUE TITLE
Dead link to DropHandlerExample in README.md

### ISSUE THREAD

**Issue by rillig** [punker76/gong-wpf-dragdrop#210]
The link points to a 404 page. I clicked it while looking for the nice-looking application from which the screenshots above were taken. Does this example application still exist, and if it does, where?

**Comment by punker76** [comment]
@rillig Uups, just forgot to fix this link. I completely chnaged the examples. You can look at the new one here https://github.com/punker76/gong-wpf-dragdrop/tree/dev/src/Showcase.WPF.DragDrop.NET45.
A compiled executable can be found at the last release https://github.com/punker76/gong-wpf-dragdrop/releases

**Comment by punker76** [comment]
readme updated
