### ISSUE TITLE
ListBox DragDropKeyStates example moves when being told to copy

### ISSUE THREAD

**Issue by rillig** [punker76/gong-wpf-dragdrop#211]
Version: 513fb18b859fb095ffde7281bddf1e0216222476

- Run the Showcase application
- Select ListBox > DragDropKeyStates from the menu
- Set DragDropCopyKeyState to LeftButton
- Drag one item from the left list to the right list

The mouse cursor clearly says “copy”, but the actual action is to move the item. After dropping, it is no longer in the left list.

**Comment by punker76** [comment]
@rillig I know :-( -> https://github.com/punker76/gong-wpf-dragdrop/issues/200
