### ISSUE TITLE
No Handler is called if ListView is inside Expander in DataTemplate

### ISSUE THREAD

**Issue by pwoestmann** [punker76/gong-wpf-dragdrop#212]
Hey really great work so far !

Im expecting an Issue when using multiple ListViews wrapped in an expander where Items shall be dragged between.

My Models are three Collections of Classes where the view is bound to.

class Geometry 
      -Name Property

class Target 
    -Name Property

class Path 
       -Name Property
       -tbTargets "ICollection of Target"

My ViewModel has the Models as  three Properties

ObservableCollection<Geometry> Geometries
ObservableCollection<Target> Targets
ObservableCollection<Path> Paths

My View is of the following structure
`<UserControl.Resources>

        <DataTemplate x:Key="GeometryTemplate">
           <Label Content="{Binding Name}" />
        </DataTemplate>
        
        <DataTemplate x:Key="TargetTemplate">
            <Label Content="{Binding Name}" />
        </DataTemplate>
        
        <DataTemplate x:Key="PathTemplate">
            <Expander Header="{Binding Name}">
                <ListView ItemsSource="{Binding tbTargets}" ItemTemplate="{StaticResource TargetTemplate}" dd:DragDrop.IsDragSource="True" dd:DragDrop.IsDropTarget="True" dd:DragDrop.DropHandler="{Binding}" dd:DragDrop.DragHandler="{Binding}" />
            </Expander>
        </DataTemplate>
        
        <Style TargetType="{x:Type Expander}" BasedOn="{StaticResource {x:Type Expander}}">
            <Setter Property="Background" Value="{DynamicResource WhiteBrush}"/>
            <Setter Property="BorderBrush" Value="{DynamicResource WhiteBrush}"/>
        </Style>
        
    </UserControl.Resources>
    
    
    <Grid>
        <StackPanel Orientation="Vertical">
            <Expander Header="Geometries">
                <ListView ItemsSource="{Binding Geometries}" ItemTemplate="{StaticResource GeometryTemplate}" MaxHeight="200" dd:DragDrop.IsDragSource="True" dd:DragDrop.IsDropTarget="True" dd:DragDrop.DropHandler="{Binding}" dd:DragDrop.DragHandler="{Binding}"/>
            </Expander>
            <Expander Header="Targets">
                <ListView ItemsSource="{Binding Targets}" ItemTemplate="{StaticResource TargetTemplate}" MaxHeight="200" dd:DragDrop.IsDragSource="True" dd:DragDrop.IsDropTarget="True" dd:DragDrop.DropHandler="{Binding}" dd:DragDrop.DragHandler="{Binding}"/>
            </Expander>
            <Expander Header="Paths">
                <ListView ItemsSource="{Binding Paths}" ItemTemplate="{StaticResource PathTemplate}" MaxHeight="200" dd:DragDrop.IsDragSource="True" dd:DragDrop.IsDropTarget="True" dd:DragDrop.DropHandler="{Binding}" dd:DragDrop.DragHandler="{Binding}"/>
            </Expander>
       </StackPanel>
    </Grid>
</UserControl>`

If i drag between the Geometries and Targets collection the Drag Handler is called, when im dragging in the Paths child collection not. Is this an issure or am I doing something wrong?

Thank you very much in advance

**Comment by punker76** [comment]
@pwoestmann Which version do you use?

**Comment by pwoestmann** [comment]
Sorry for the missing information, my bad :(
Windows 7 Pro
.Net 4.6
Gong 1.0.0.0 from Nuget 2016-09-02

**Comment by punker76** [comment]
@pwoestmann Hi, please take a look at https://github.com/punker76/gong-wpf-dragdrop/pull/214 which will probably fix this issue.

You can grab the alpha nuget package and test sample from here https://ci.appveyor.com/project/punker76/gong-wpf-dragdrop/build/1.1.0-alpha3-hwpiijyw/artifacts

![2016-09-26_16h22_44](https://cloud.githubusercontent.com/assets/658431/18837811/796cfcce-8405-11e6-8166-7520217a3d14.png)

Please let me know if it fixes the issue, thx.

**Comment by pwoestmann** [comment]
Hey thank you for your fast reply.
But unfortunately the drags and drops inside the Listview in the datatemplate are still not beding handled.

Abstracted into the  the picture above:
SubItem0 would be a listView with a ListView of Labels inside.
Draggin SubItem will fire the event, A drag of a label inside the list of SubItem will not.

**Comment by punker76** [comment]
@pwoestmann 

> Maybe there is a problem researching the Handle in the inherited Item by dd:DragDrop.DropHandler="{Binding}" ? Is there a way to Provide the name of the Handle like {Binding Viewmodelname.DragOver}?

Yeah the binding could be the problem. Is there any Bindingexpression Debug output? `dd:DragDrop.DropHandler="{Binding}"` means you bind to the DataContext of the container (DataTemplate). Can you create a short repo at your github account?

**Comment by pwoestmann** [comment]
Ive managed to get it working!
I forgot about the missing connection between the DataTemplate and parent element DataContext . So if i set the Handlers to:

`dd:DragDrop.DropHandler="{Binding DataContext,RelativeSource={RelativeSource Mode=FindAncestor, AncestorType=UserControl}}"
                          dd:DragDrop.DragHandler="{Binding DataContext,RelativeSource={RelativeSource Mode=FindAncestor, AncestorType=UserControl}}" />`

everything works as expected and very awesome!

I would like to apologize myelf for insinuating errors in your code :( 
Maybe you add this trick to the documentation.

Thank you very much for your fast and professional help.

**Comment by punker76** [comment]
@pwoestmann Thx. And you don't need to apologize yourself. I'm also not perfect ;-) I will add a note to this if someone uses only one DragHandler/DropHandler.
