### ISSUE TITLE
Support for ControlTemplate types

### ISSUE THREAD

**Issue by guidoauchli** [punker76/gong-wpf-dragdrop#213]
Dear punker76, thank you much for this great project - I'm enjoying it.
I was using the previous  version 0.1.4.3 and now just updated to the current version. There is a thing that doesn't work like it did before and might be an issue:

A ListBox uses as ItemTemplate a ControlTemplate of a RadioButton control. Dragging does not start anymore (CanStartDrag doesn't get called).

PS: I tested the code with other controls that handle click events (Button, Checkbox) - same issue. But a Border or a TextBlock do work.

**Comment by pwoestmann** [comment]
This behavior sounds familiar to the issues im expecting with templates and inherited controls: https://github.com/punker76/gong-wpf-dragdrop/issues/212

**Comment by punker76** [comment]
@guidoauchli Hi, please take a look at https://github.com/punker76/gong-wpf-dragdrop/pull/214 which will probably fix this issue.

You can grab the alpha nuget package and test sample from here https://ci.appveyor.com/project/punker76/gong-wpf-dragdrop/build/1.1.0-alpha3-hwpiijyw/artifacts

![2016-09-26_16h22_44](https://cloud.githubusercontent.com/assets/658431/18837811/796cfcce-8405-11e6-8166-7520217a3d14.png)

Please let me know if it fixes the issue, thx.

**Comment by guidoauchli** [comment]
Great, the 1.1.0 alpha version does fix this issue. :-)
