### ISSUE TITLE
DefaultDragAdorner is not visible if multiple Items selected in DataGrid

### ISSUE THREAD

**Issue by juergschweigi** [punker76/gong-wpf-dragdrop#215]
Hallo dev,
i'm using your FrameWork and it works fine, but I miss the DefaultDragAdorner in Datagrid if i want to drag multiple selected Items.
For one selected Item it works fine.
Is there a Possibility for me to get a DragAdorner for multiple selected Items of a DataGrid like one selected Item???

Secondly:
I want to show the DragAdorner over all visible controls with using the EffectNoneAdorner instead of the Default MouseIcon.
Is this possible???

Greeting Jürgen

**Comment by punker76** [comment]
@juergschweigi Dragging multiple selected items should work. Do you set the `SelectionMode` to `Extended`? The second one is currently not available, but it's noticed.

**Comment by juergschweigi** [comment]
Yes, i have Set the selectionmode in datagrid to extended. Do i have to Set a Property in drag&drop-framework?
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 11.10.16, 16:51, Jan Karger <notifications@github.com> schrieb:

  
    
      @juergschweigi Dragging multiple selected items should work. Do you set the SelectionMode to Extended? The second one is currently not available, but it's noticed.

**Comment by punker76** [comment]
@juergschweigi The DefaultDragAdorner is not used for multiple item selection. I will add a new property to allow setting a template which is used for multiple selection. -> https://github.com/punker76/gong-wpf-dragdrop/issues/228
