### ISSUE TITLE
Drag/Drop on a button

### ISSUE THREAD

**Issue by ixshariff** [punker76/gong-wpf-dragdrop#216]
Hi,

I have a dockpanel with a background image and a transparent button that fills the dockpanel (last fill child). I use the click handler on the button to edit the image. All works fine.

I now want to drag and drop these images. However, it doesn't start the the drag operation. It seems like the button is swallowing the event. Any ideas how I could fix this?

Thanks,

Irfan

**Comment by punker76** [comment]
@ixshariff Which version do you use?

**Comment by ixshariff** [comment]
Hi, 
Thanks for your reply. version 1.0.0

**Comment by punker76** [comment]
@ixshariff Can you create a short sample for this issue?

**Comment by ixshariff** [comment]
Hi, 
Here is an example. Replacing the button with a label works but the button doesn't.

[DragDropExample.zip](https://github.com/punker76/gong-wpf-dragdrop/files/522332/DragDropExample.zip)

**Comment by ixshariff** [comment]
Hi Jan,
Any news on a fix for this? Any help much appreciated.
Thanks
Irfan

**Comment by punker76** [comment]
@ixshariff Yes, cause I'm stupid. I already fixed this, but does not publish a new alpha... https://github.com/punker76/gong-wpf-dragdrop/pull/214

**Comment by punker76** [comment]
@ixshariff fixed with https://github.com/punker76/gong-wpf-dragdrop/pull/214

[DragDropExample.zip](https://github.com/punker76/gong-wpf-dragdrop/files/526477/DragDropExample.zip)

![buttondrag](https://cloud.githubusercontent.com/assets/658431/19340660/5eefa658-912a-11e6-95b3-5bce44f015cb.gif)

**Comment by ixshariff** [comment]
Hi Jan,

That looks awesome man! Thank-you. Any ideas when v1.1.0 will be formally released?

One other question for you. Is there any way of stopping the insertion adorner displaying when dragging first item to the first location (i.e. dragging it to where it already is). Same with the last one? Does that make sense?

**Comment by ixshariff** [comment]
Hi Jan,
Any news on when there might be a formal release?
