### ISSUE TITLE
Drag and Drop in ListBox with custom DataTemplate not working.

### ISSUE THREAD

**Issue by abinmatthew** [punker76/gong-wpf-dragdrop#217]
I have attached the sample project which demonstrate the issue.
previous version(0.1.4.3) works fine with the same example.

[WpfApplication1.zip](https://github.com/punker76/gong-wpf-dragdrop/files/536373/WpfApplication1.zip)

**Comment by punker76** [comment]
@abinmatthew It's already fixed with https://github.com/punker76/gong-wpf-dragdrop/pull/214 next version is coming soon
