### ISSUE TITLE
Drag n Drop NOT WORKING on multiple Templates UserControl inside Listview

### ISSUE THREAD

**Issue by diablade** [punker76/gong-wpf-dragdrop#220]
it appear that when you using an **ListView** with **ItemTemplateSelector**
for multiple different **UserControl** inside the listview 
it stoped the drag n drop working
even the 
`dd:DragDrop.DragSourceIgnore = "false"` on the templates...
doesnt make it work

but actually you can grab the item on the blank spaces inside of the item , (like cliking on the padding of the item, but not on the templates)
i did it on the actual showcase src.

for info: 
(my listview source item is an `ObservableCollection<ParentObject>`
and all the templates for the listview are UserControls, Datatemplate with ChildObjects model that inherits the ParentObject model)

**Comment by punker76** [comment]
@diablade Can you create an app with this short sample?

**Comment by diablade** [comment]
yes i can 
but actually i finally test your Dev branch and the problem was already solved 
can you implement it in the master for an upadate nuget package ? 
thank you so much for that hudge work of yours 
this lib is soooo cool and relieve me a lot of works :))))

**Comment by punker76** [comment]
@diablade v1.1.0 is upcoming

**Comment by diablade** [comment]
thanks you so much =)
