### ISSUE TITLE
Application crashes with nested drag source

### ISSUE THREAD

**Issue by ShadowDancer** [punker76/gong-wpf-dragdrop#227]
Hello,
I have TreeView in which all leaves may contain listview of items. Looks like dragdrop library is doing something wrong, as after selecting all items in listview and I doubleclick it I am getting InvalidOperationException("Property SelectedItem was registered as readonly and cannot be modified without authroization key"). How I can get around this error?

`   in System.Windows.DependencyObject.SetupPropertyChange(DependencyProperty dp)
   in System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   in GongSolutions.Wpf.DragDrop.Utilities.ItemsControlExtensions.SetSelectedItem(ItemsControl itemsControl, Object item) w D:\projects\git\gong-wpf-dragdrop\src\GongSolutions.WPF.DragDrop\Utilities\ItemsControlExtensions.cs:wiersz 292
   in GongSolutions.Wpf.DragDrop.DragDrop.DragSource_PreviewMouseLeftButtonUp(Object sender, MouseButtonEventArgs e) w D:\projects\git\gong-wpf-dragdrop\src\GongSolutions.WPF.DragDrop\DragDrop.cs:wiersz 782
   in System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   in System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   in System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)`

https://github.com/punker76/gong-wpf-dragdrop/blob/dev/src/GongSolutions.WPF.DragDrop/Utilities/ItemsControlExtensions.cs#L292

There is repro project:
https://github.com/ShadowDancer/DragDropBugDemo

**Comment by punker76** [comment]
@ShadowDancer Thx for the repro project! This issue is fixed now and will be available in v1.1.0

**Comment by ShadowDancer** [comment]
@punker76 Thanks! Can I use current head without suprises instead of nuget package?

**Comment by punker76** [comment]
@ShadowDancer Yes, should be working
