### ISSUE TITLE
how can I drag a Button and drop it into a list to add new item ? 

### ISSUE THREAD

**Issue by diablade** [punker76/gong-wpf-dragdrop#232]
I would like to grab an button and add some new item in the list 
without of course removing the button 

my button already add new specific item by clicking on it 
but how to do it with your solution with dragNdrop ? 
(because it is very handy to grab directly the button and add new item in the list directly to the position you need)
(the adorner can be the same as the button dragged)

actually I have many buttons that add different kind of item in the list 

thanks in advance

**Comment by diablade** [comment]
shoud i implement IDragInfo on an custom Button class ? 
and force new item inside Data ? 

or 

should i do it with itemsControls and put inside some buttons to do the job for click
but then how to force only copy to the target list (to prevent from removing them) 
because i want the buttons stay in place 
it is like a source for adding item in the target list 

can someone help me with this ? 
I'm kind of a newbie here :/

thanks

**Comment by punker76** [comment]
@diablade Is this still an issue for you?

**Comment by diablade** [comment]
yes it is

**Comment by punker76** [comment]
@diablade Would be nice if you can create a sample for this issue, so I can debug and maybe find what's going wrong. thx.

**Comment by diablade** [comment]
you didnt read my post
it is more an feature then a bug 
and / or more like a question for doing it

**Comment by punker76** [comment]
@diablade Hope I undertstand this correctly. You want to start a drag operation on the button with a new item and then drop this new item on the list? If so, then you can implement the IDragSource and create the item on the StartDrag method and save it as Data for the Drag&Drop process.
