### ISSUE TITLE
DragAdornerTemplate gets cut off with negative margins

### ISSUE THREAD

**Issue by brather1ng** [punker76/gong-wpf-dragdrop#237]
## What steps will reproduce this issue?

Clone and run https://github.com/brather1ng/GongDragAdornerIssue. Drag the brown rectangle in the middle.

The rectangle in the DragAdornerTemplate is cut off instead of being moved by the negative left margin.

It was hard to reproduce this:

- Without MahApps.Metro, it works fine.
- With small changes (not enough to allow me to do what I want to) it also works. E.g. replace the `Width="{Binding Image.Width}"` with `Width="94"` and it works.

So it seems to be some kind of really weird interaction between MahApps.Metro, Gong DragDrop and specific types of properties.

### Expected outcome

The rectangle should be offset to the left and not cut off.

### Repo

https://github.com/brather1ng/GongDragAdornerIssue

### Environment

- MahApps.Metro __v1.4.3__
- GongSolutions.WPF.DragDrop __v1.1.0__
- Windows OS __10__
- Visual Studio __2015__
- .NET Framework __4.5.2__

**Comment by punker76** [comment]
@brather1ng Thx for the sample! You can move the adorner by setting the `dd:DragDrop.DragMouseAnchorPoint` e.g.

```xaml
<UserControl x:Class="GongDropAdornerIssue.View"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:dd="urn:gong-wpf-dragdrop"
             xmlns:local="clr-namespace:GongDropAdornerIssue"
             dd:DragDrop.IsDragSource="True"
             dd:DragDrop.DragMouseAnchorPoint=".3 1"
             dd:DragDrop.DragHandler="{Binding}">
    <UserControl.DataContext>
        <local:ViewModel />
    </UserControl.DataContext>
    <dd:DragDrop.DragAdornerTemplate>
        <DataTemplate DataType="local:ViewModel">
            <Rectangle Fill="Aqua"
                       Width="{Binding Image.Width}"
                       Height="94"
                       Margin="0 0 0 0" />
        </DataTemplate>
    </dd:DragDrop.DragAdornerTemplate>
    <Rectangle Fill="Brown"
               Width="94"
               Height="94" />
</UserControl>
```

this means 0.3 x the adorner width to the left of the mouse point and 1 x height to the top.

![image](https://cloud.githubusercontent.com/assets/658431/23484330/d034228e-fed6-11e6-83b7-412ec40dd421.png)

**Comment by brather1ng** [comment]
Thanks! Missed that property, it's a much better solution than the margin stuff I tried to do.
