### ISSUE TITLE
Drag a listbox item that has its own listbox inside

### ISSUE THREAD

**Issue by Haukinger** [punker76/gong-wpf-dragdrop#242]
This can be done currently (e.g. in the showcase app), but you have to click _outside_ of any inner listbox item (yet inside the outer listbox item). You cannot start a drag of an outer listbox item from a click on an inner listbox item.

I'd like to have the possibility to

- either tell the framework to ignore the inner listbox (because I do not want to drag the inner items)
- or have the framework automatically ignore listboxes that aren't marked with IsDragSource=true

when looking up the item container.

I've implemented the first option as a new IsUndraggableListbox attached property, but I'd rather prefer the latter option.

**Comment by punker76** [comment]
@Haukinger Did you test the existing attached property `DragSourceIgnore` ?

**Comment by Haukinger** [comment]
@punker76 That was in fact my first idea, but it removes dragging altogether. With DragSourceIgnore set on the inner listboxes, I cannot even drag when clicking outside the inner listbox items.

**Comment by punker76** [comment]
@Haukinger Can you create a short sample for this issue, which looks similar to your original app? thx.

**Comment by Haukinger** [comment]
@punker76 Sure thing, but probably not before this evening. Until then, you can use the existing List-in-List example, just remove the dd:DragDrop stuff from the inner listboxes and put it in the outer listbox.

**Comment by Haukinger** [comment]
@punker76 I've added the sample to the demo-app in a branch on my fork: [Haukinger/gong-wpf-dragdrop/#242](https://github.com/Haukinger/gong-wpf-dragdrop/tree/%23242)

**Comment by punker76** [comment]
@Haukinger Can you check if this branch work for you? thx. https://github.com/punker76/gong-wpf-dragdrop/tree/Hittest-DragDrop-start-fixes

**Comment by punker76** [comment]
![dragdrop_listinlist](https://cloud.githubusercontent.com/assets/658431/25410415/edff5b06-2a16-11e7-846a-625f1c89aeb7.gif)

**Comment by Haukinger** [comment]
@punker76 Works great, thanks a lot!
