### ISSUE TITLE
Dragging an item over a nested ListView which is not a DropTarget will use it as target instead of parent

### ISSUE THREAD

**Issue by Mertsch** [punker76/gong-wpf-dragdrop#244]
Repo:
1. Run Showcase.WPF.DragDrop.NET45 from https://github.com/Mertsch/gong-wpf-dragdrop
2. Select "Fixed #Issues"
3. Select #146
4. Drag and Drop an item from left to right
5. Select #244

6. Try to Drop an item from the left side onto the right side
it only works when dropping onto the "Root" item
Expected: It should also work on the inner "Item" box, as it is *not* marked as DropTarget and thus be ignored

**Comment by Mertsch** [comment]
@punker76 I am having some issues while verifying the fix, I can't point a finger on something specific, yet but it seems there is an issue with `<UniformGrid/>`

I have a `ListView` with an `UniformGrid` as `ItemsPanel` which leads to a horizontal first, then vertical layout. When there are no nested items the position is calculated perfectly and Drop targets the correct element.
When I Drag over the nested `ListView` with `<StackPanel VerticalAlignment="Bottom"/>`, which should be ignored, the target calculation for the `UniformGrid` is confused and DnD does not work or the target is a different item then the one dragged over.

@punker76 Have an idea what might be the cause?

**Comment by punker76** [comment]
@Mertsch That's really a special thing. Seems like you must implement your own DropTargetAdorner which handles the insertion (highlighting).
