### ISSUE TITLE
scrollViewer not acount for header

### ISSUE THREAD

**Issue by JonasBM** [punker76/gong-wpf-dragdrop#250]
Hi, sorry in advance, not a native english speaker

I look and dont find this problem in issues, sorry if as already resolved.

When calling Scroll up, scrollViewer dont account for headers, so if has a header it wont go up.
I am not a great developer, its morre a hobby, my solution was the follow:

in the class "DragDrop" in method "Scroll(DropInfo dropInfo, DragEventArgs e)"
add after "var scrollViewer =..."
`var scrollContentPresenter = scrollViewer.GetVisualDescendent<ScrollContentPresenter>();`

change all scrollViewer to scrollContentPresenter in this method, except:
```
scrollViewer.FontSize
scrollViewer.LineRight();
scrollViewer.LineLeft();
scrollViewer.LineDown();
scrollViewer.LineUp();
```

I cound have make the change on code and sand, but my code is not as elegant as yours, its just a simple solution for my problem.

Thanks, and keep the good work!

ps.: i have the DragDrop in a DataGrid with header.

**Comment by punker76** [comment]
@JonasBM What do you mean with a "header"? Can you create a short simple sample and put it on GitHub? Thx

**Comment by JonasBM** [comment]
Hi, i have made the sample
[WpfApplication1](https://github.com/JonasBM/WpfApplication1)

And a image with the header selected:
![image](https://user-images.githubusercontent.com/8902043/28681076-9f0f5950-72ce-11e7-93aa-13eb547108dd.png)

Thanks
