### ISSUE TITLE
OverrideCursor not being cleared

### ISSUE THREAD

**Issue by Trakcf** [punker76/gong-wpf-dragdrop#256]
When a drag is released over itself or some other item that is not a valid drop target the Mouse.OverrideCursor is never cleared out like it is on a successful drop.  I overrode the DragCancelled function in my program to do this but it should probably get cleared out somewhere in the default handler as well so the cursor isn't stuck as an arrow.  Something like,

public virtual void DragCancelled()
{
      if (Mouse.OverrideCursor != null)
      {
        Mouse.OverrideCursor = null;
      }
}

**Comment by punker76** [comment]
@Trakcf Can you create a sample which shows this issue? With which version does this happen?
