### ISSUE TITLE
ListBox with SelectionMode=Extended issue

### ISSUE THREAD

**Issue by ekalchev** [punker76/gong-wpf-dragdrop#257]
When I have list box with multiple items selected and I click on a item that is part of the selection, the item is not selected and multi selection is lost. Default behavior of ListBox is to select clicked item. Also, if you have buttons inside the listboxitem they also don't work.

**Comment by punker76** [comment]
@ekalchev Can you provide me more information?

# PLEASE READ BEFORE POSTING AN ISSUE

### Seriously consider creating and linking to a test repo which takes absolutely minimal setup to illustrate how reproduce the problem.

My time is limited and .Zip files, code snippets and partial examples are often a time sink. GitHub also provides great communication and code review tools which can be utilised.

## HOW TO POST A GOOD SAMPLE.

Follow these guidelines and I will most likely look at the issue sooner:

* Post a full GitHub repository. Not a zip file, half baked snippet etc. If GitHub is new to you consider it a great learning opportunity and chance to get involved.
* The repository should have just ONE step max for me to get running, and that is "Restore NuGet Packages". If there are any other missing dependencies, or uncompiling features I will most likely move on to another issue.
* I'm not trying to be awkward. I'm just busy and I'm helping a lot of people, not just you, so help me out and I will help you out.

## What steps will reproduce this issue?

_Write problem description here_

### Expected outcome

_Write expected outcome here_

### Repo

_Link to the Repo_

### Environment

- GongSolutions.WPF.DragDrop __v?.?.?__
- Windows OS __??__
- Visual Studio __20xx__
- .NET Framework __?.?__

**Comment by ekalchev** [comment]
I am using latest version of GongSolutions.WPF.DragDrop
Visual Studio 2015
.NET Framework 4.6

I can see the problem is here

if (itemsControl is MultiSelector) {
        ((MultiSelector)itemsControl).SelectedItem = null;
        ((MultiSelector)itemsControl).SelectedItem = item;
      } else if (itemsControl is ListBox) {
        var selectionMode = ((ListBox)itemsControl).SelectionMode;
        try {
          // change SelectionMode for UpdateAnchorAndActionItem
          ((ListBox)itemsControl).SelectionMode = SelectionMode.Single;
          ((ListBox)itemsControl).SelectedItem = null;
          ((ListBox)itemsControl).SelectedItem = item;
        }

SelectedItem = null 
is setting the selected item to null
but 
.SelectedItem = item

but this line is not setting SelectedItem to Item. I can see Item has the correct value but it is not getting set to SelectedItem. Probably some check inside SelectedItem setter is preventing this. May be related to WPF 4.5 changes for the list box?

**Comment by ekalchev** [comment]
The problem is not in GongSolutions.WPF.DragDrop. I have custom implementation of ICollectionView and Contains method was not implemented which was causing this side effect. Selection now works but I still struggle with GongSolutions.WPF.DragDrop code that handles clicks when there is a multiple selection. Handling mouse down events for the selected items prevent me from having commands trigger for the buttons inside the selected treeview items. Any idea how I can achieve that with GongSolutions.WPF.DragDrop?

**Comment by Insire** [comment]
This lib does not interfere with click events regardless of if your listbox uses multi selection or not.

As punker suggested, having a repo showcasing your issue would help a lot in supporting you with your issue.

**Comment by punker76** [comment]
@ekalchev as @Insire wrote, a small app which demonstrates your issue would be nice. Cause multiple selection should work as you can see and test in the main showcase app. also having buttons or combobox or textbox inside items is also possible.

**Comment by punker76** [comment]
@ekalchev Any news for a repo app?
