### ISSUE TITLE
Ctrl-Click and drag only drags most recently selected item

### ISSUE THREAD

**Issue by bozalina** [punker76/gong-wpf-dragdrop#264]
## What steps will reproduce this issue?

1. Run the Gong showcase in the Gong solution and select the ListBox, Bound example
2. In the left ListBox, control click items 1 and 2 to select them
3. When you click item 2, don't release the mouse button and instead drag the selected items to the right ListBox
4. Only item 2 appears in the right ListBox

### Expected outcome

Items 1 and 2 appear in the right ListBox

### Environment

- GongSolutions.WPF.DragDrop __v1.2.0__
- Windows OS __7__
- Visual Studio __2017__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@bozalina Ok, found it. I will fix it in 1.2.0

**Comment by bozalina** [comment]
@punker76 thank you for the quick turnaround on the last bug I filed, it's greatly appreciated.  Do you have an ETA for the fix in 1.2?

**Comment by punker76** [comment]
@bozalina I'll create an alpha version tonight (GER)
