### ISSUE TITLE
Increase major on breaking changes

### ISSUE THREAD

**Issue by jogibear9988** [punker76/gong-wpf-dragdrop#274]
as you added a method to an interface, will you increase major version, because this is a breaking change if someone used the interface directly!

**Comment by jogibear9988** [comment]
see http://semver.org

**Comment by punker76** [comment]
@jogibear9988 Yes, I'll do this

**Comment by punker76** [comment]
9ab121291ee40fe98d5670e887bdfbd484dfb7a4
