### ISSUE TITLE
Force drag start for specific controls

### ISSUE THREAD

**Issue by punker76** [punker76/gong-wpf-dragdrop#277]
Sometimes it's necessary to allow dragging from specific controls like `TextBox` or `RichTextBox`. This isn't allowed with the current implementation.

https://github.com/punker76/gong-wpf-dragdrop/blob/9ab121291ee40fe98d5670e887bdfbd484dfb7a4/src/GongSolutions.WPF.DragDrop.Shared/DragDrop.cs#L354-L370

To allow this, I can add an attached property which forces the start drag for such a control.

/cc @nmfisher

**Comment by smnrock** [comment]
What is the reason behind restricting these controls as dragsource?  I needed a textbox to be a dragsource, but due to above code its not working.  I had to add an extra property to do force drag/skip the above conditions.   Will there be a any unexpected issue due to this change?

**Comment by punker76** [comment]
A TextBox can be used without any attached property to use the drag&drop mechanism from it.

Then you can handle the drop like this:

```csharp
/// <inheritdoc />
public void Drop(IDropInfo dropInfo)
{
    var textBox = (TextBox)dropInfo.VisualTarget;

    if (dropInfo.Data is IDataObject dataObject)
    {
        if (dataObject.GetDataPresent(DataFormats.Text))
        {
            textBox.Text = dataObject.GetData(DataFormats.Text) as string ?? string.Empty;
        }
    }
}
```
