### ISSUE TITLE
Selecting Top only control

### ISSUE THREAD

**Issue by mrbrennonwilliams** [punker76/gong-wpf-dragdrop#281]
Hi,

I have  user control that is an Item in a bound itemscontrol. When I drag the user control, the entire collection is selection, not just the top most user control in the collection.

Is this a known issue, or is this me to setting a binding correctly?

The user control is not set as a drag source etc.

Thanks for your help.

**Comment by punker76** [comment]
@mrbrennonwilliams What did you mean with "the entire collection is selection"? Normally if you drag an item, the item itself is the VisualSourceItem item container and the SourceItem / SourceItems the data behind that. Is it possible for you to create a short sample? Or just make a screencast?

**Comment by mrbrennonwilliams** [comment]
Hi @punker76 

Thanks for getting back to me.

The issue is detailed in #280 where there is a screen shot of the image element being dragged, and the entire collection going with it.

I have managed to work around the problem detailed in that issue in terms of the error being raised, but the top element problem I listed here is still present.

Cheers

**Comment by punker76** [comment]
@mrbrennonwilliams Ok, maybe I understand now what you are doing. You try to add the visual item on the collection (the ItemsSource, not the Items property)...?

**Comment by mrbrennonwilliams** [comment]
@punker76 correct. That is working correctly in terms of type restrictions, add/remove etc.

**Comment by mrbrennonwilliams** [comment]
this is the code in my IDropTarget for Drop

`

public void Drop(IDropInfo dropInfo)
{
    object sourceItem = dropInfo.Data;

    if (dropInfo.TargetCollection != null)
    {
        //The collection the control is coning from
        if (dropInfo.DragInfo.SourceCollection != null)
        {
            if (dropInfo.DragInfo.SourceCollection is ItemCollection)
                (dropInfo.DragInfo.SourceCollection as ItemCollection).Remove(sourceItem);
            else
                (dropInfo.DragInfo.SourceCollection as IList).Remove(sourceItem);

            //This is this collection of items, which is bound back to our OC columnItems
            if (dropInfo.TargetCollection != null)
            {
                if (dropInfo.TargetCollection is ItemCollection)
                    (dropInfo.TargetCollection as ItemCollection).Insert(dropInfo.InsertIndex, sourceItem);
                else
                    (dropInfo.TargetCollection as IList).Insert(dropInfo.InsertIndex, sourceItem);
            }            
        }
    }
}
`

**Comment by punker76** [comment]
@mrbrennonwilliams If you use the ItemsSource (with e.g. an ObservableCollection), then you should add/remove the item (the data) and not the VisualSourceItem.

**Comment by mrbrennonwilliams** [comment]
@punker76 the sourceItem is coming from dropInfo.Data, which is the actual control, rather than a bound data object. Because of the complexity of this solution, the data models are extracted away - the controls are generated dynamically, rather than using a template selector in data binding.

Are you saying that there is some visual reference that is not being released from the source to target collection?

I would have thought this is more to do with the hittesting of the control itself ?

Thanks BTW for the help.

**Comment by punker76** [comment]
@mrbrennonwilliams So you have your own IDragSource implementation which creates a control and set this to the Data property?

**Comment by mrbrennonwilliams** [comment]
@punker76 unfortunately not - the controls are generated by a renderer and it inserts the control directly into the observablecollection that is bound to the itemscollection

**Comment by punker76** [comment]
@mrbrennonwilliams ...but your ObservableCollection is from another type, maybe the data behind, so you can't add a generated visual item...

**Comment by mrbrennonwilliams** [comment]
@punker76 the user controls all inherit an Interface, that is the type that the observableCollection has which allows them to be different controls

**Comment by punker76** [comment]
@mrbrennonwilliams We (you/I) should create a short sample for this scenario... which hopefully shows this exception from #280 too

**Comment by mrbrennonwilliams** [comment]
@punker76  no worries. I will try to get a sample together on another fork (my luck it will all be perfect ;-) and wont show the error)

As I said, I'm sure its something stupid on my part, rather than it being an issue with the library, but for the life of me, I cant solve it.

Will let you know when I get that sample up.

Cheers

**Comment by punker76** [comment]
@mrbrennonwilliams cool, thx! 👍
