### ISSUE TITLE
DragAdorner not moving out of parent window to child window

### ISSUE THREAD

**Issue by ayyappangs** [punker76/gong-wpf-dragdrop#282]
I am trying to drag an item from a listbox and move it to another window. DragAdorner is working fine in the parent window, But it is not moving out the parent window to the child window. I have attached a zipfile which illustrates my problem. 
[GongDragDrop_Learning.zip](https://github.com/punker76/gong-wpf-dragdrop/files/1507776/GongDragDrop_Learning.zip)

**Comment by punker76** [comment]
@ayyappangs I don't know where you are got the v1.1.5, but if you use the official latest v1.1.0 you will get this result...

![gong_dragdrop_window2window](https://user-images.githubusercontent.com/658431/33308897-886322a4-d41c-11e7-9ad8-06845ee9ad51.gif)

Here is the minor changed sample

[GongDragDrop_Learning_withGongv1.1.0.zip](https://github.com/punker76/gong-wpf-dragdrop/files/1508935/GongDragDrop_Learning_withGongv1.1.0.zip)
