### ISSUE TITLE
Drag&Drop within the same Control (ItemsControl) calls Remove & Add

### ISSUE THREAD

**Issue by xDGameStudios** [punker76/gong-wpf-dragdrop#288]
I'm trying to catch the Drag&Drop event within a ItemsControl I'm using and to do this I listen to the ObservableCollection CollectionChanged event. But the drag and drop always removes the item and then adds the item. Is there a way to make it so it uses the Move method instead... as it would be better to differentiate from the Add Item and Remove Item functionality I already implemented.

Thank you so much! (and sorry for not following the post recommendations but it is not really a bug or a issue.. is more like a question)

**Comment by punker76** [comment]
@xDGameStudios You can make your own IDropTarget or derive from DefaultDropHandler and handle the Drop by yourself.

**Comment by uecasm** [comment]
For reference, this is an example implementation which performs this optimisation (for single-select lists only, though you could probably extend it to support multi-select).

It would be nice if something similar could be included in `DefaultDropHandler` in some future version... :wink: 

    public override void Drop(IDropInfo dropInfo)
    {
        var source = dropInfo.DragInfo.SourceCollection.TryGetList();
        var target = dropInfo.TargetCollection.TryGetList();

        if (target != null && ReferenceEquals(source, target))
        {
            var insertIndex = dropInfo.InsertIndex;
            if (insertIndex > dropInfo.DragInfo.SourceIndex) --insertIndex;
            if (insertIndex == dropInfo.DragInfo.SourceIndex) return;

            var moveMethod = target.GetType()
                .GetMethod("Move", new[] { typeof(int), typeof(int) });
            if (moveMethod != null)
            {
                moveMethod.Invoke(target,
                    new object[] { dropInfo.DragInfo.SourceIndex, insertIndex });
                return;
            }
        }

        base.Drop(dropInfo);
    }

I haven't tested it on sorted/filtered lists; it might require some more magic to handle those properly.
