### ISSUE TITLE
Drag Over IDropInfo InsertIndex does not match Drop IDropInfo InsertIndex

### ISSUE THREAD

**Issue by csjasnoch** [punker76/gong-wpf-dragdrop#289]
The DropTargetAdorner is of course set to a "Insert" and we would expect as the user drags above and bellow and object the value changes.  It does not. I had thought perhaps the DragOver was not being called and was waiting for a drag to another object in the collection, but a simple counter on the DestinationText shows this is not the case.

Why is this a concern?
We were wanting to display the index to the user, so programmatically the DestinationText is updated using the InsertIndex.
e.g.
    $"Index ({dropInfo.InsertIndex}) COUNTER${_counter++}"

The counter showed us that the DragOver is most certainly called. If I drag above and bellow an object (e.g. 5 objects and I grab index 0, and drag to the end of the collection it may say index 4, 5, or even 3. Once I am in the position I can drag to what should be index 3, and back and forth between expected "3" and "4" and see no change to the InsertIndex but the counter is going up. 

Finally, once it drops it does go to the correct place and has the correct index. So somehow the DragOver is not receiving the correct index.

To test just update the DestinationText  on the DragOver method as noted above when using DropTargetAdorners.Insert mode. Drag and object around then toggle between to spots and see that the insert value doesn't change.

**Comment by punker76** [comment]
@csjasnoch I tested this with the latest source and placed a debug line in DragOver, but I can not see what you describe. So maybe a short sample which shows this could help here.
