### ISSUE TITLE
Crash for unselect item in list

### ISSUE THREAD

**Issue by dualbios** [punker76/gong-wpf-dragdrop#290]
Crash stack trace
[crach stack trace.txt](https://github.com/punker76/gong-wpf-dragdrop/files/1994890/crach.stack.trace.txt)

## What steps will reproduce this issue?

1. Select some items in listbox. 
2. Try to deselect one of them.

## Version
1.1.0

**Comment by punker76** [comment]
@dualbios Is this reproducable in the main demo?

**Comment by punker76** [comment]
@dualbios ping

**Comment by dualbios** [comment]
@punker76 yes, it was, but i'm not able to reproduce it now.
