### ISSUE TITLE
Changing the width of dragging effect?

### ISSUE THREAD

**Issue by Tennyleaz** [punker76/gong-wpf-dragdrop#291]
I am using a listbox with drag drop. I am expecting all the dragging adorner effects to fit the width of my listbox.

The partial code of my xaml looks like:

    <ListBox Margin="0,0,0,3" Width="auto"
             IsSynchronizedWithCurrentItem="True" AllowDrop="True"
             dd:DragDrop.UseDefaultDragAdorner="True"
             dd:DragDrop.IsDragSource="True"
             dd:DragDrop.IsDropTarget="True"
             ItemContainerStyle="{StaticResource MyListBoxStyle}">
        <ListBox.ItemTemplate>
            <DataTemplate DataType="{x:Type local:PinnedNode}">
                <local:MyItemTemplate/>
            </DataTemplate>
        </ListBox.ItemTemplate>
    </ListBox>

`MyItemTemplate` is a custom user control.
The effect when dragging looks like:

![drag drop q2](https://user-images.githubusercontent.com/7089271/41076026-0b8ed644-6a42-11e8-8418-13e7696390b7.png)

How could I control the item separator adorner (?) width? I would like it to fit the entire width of my listbox.
Thank you for any ideas.

### Environment

- GongSolutions.WPF.DragDrop 1.1.0
- Windows OS 10 1803
- Visual Studio 2015
- .NET Framework 4

**Comment by punker76** [comment]
@Tennyleaz it would be nice if you can test the latest alpha gong-wpf-dragdrop v2.0.0-alpha0100. Thx!

**Comment by Tennyleaz** [comment]
I tried version `2.0.0-alpha0100`, the dragging separator effect will fit the entire width now.
Good job dev!

**Comment by punker76** [comment]
Relates to 87690a2976b70e496a2fa2949d4acf36d9690a7b
