### ISSUE TITLE
Support for StackPanel?

### ISSUE THREAD

**Issue by mrNo0b** [punker76/gong-wpf-dragdrop#299]
Is it possible to add support for StackPanel?

Its possible to use StackPanel inside ListBox and set it as IsItemsHost, but support for StackPanel by itself would be great...
```
<ControlTemplate TargetType="ListBox">
    <ScrollViewer Margin="0" Focusable="false">
        <StackPanel Margin="0" IsItemsHost="True"/>
    </ScrollViewer>
</ControlTemplate>
```

**Comment by punker76** [comment]
@mrNo0b ping
