### ISSUE TITLE
When user start drag on empty surface item is selected and dragged

### ISSUE THREAD

**Issue by petrnymsa** [punker76/gong-wpf-dragdrop#308]
## What steps will reproduce this issue?

1. Run application
2. Click and hold left mouse button under the tiles - on the white (empty surface) space.  
3. Notice that item is dragged and is possible to move it

### Expected outcome

If no item is dragged directly, it is not possible to do so. When user clicks on empty space no dragging occurs. 

### Why it is needed
Application is inspired from Windows 10 Start Menu tiles. 

### Repo

https://github.com/petrnymsa/WpfGongSolutionIssueExample

### Environment

- GongSolutions.WPF.DragDrop __v1.1.0
- Windows 10 Pro x64
- Visual Studio __2017 v 15.9.2 
- .NET Framework 4.6.1

**Comment by punker76** [comment]
@petrnymsa You can set `dd:DragDrop.DragDirectlySelectedOnly="True"` to avoid empty space dragging.

```
/// <summary>
/// Gets or Sets wheter the drag action should be started only directly on a selected item
/// or also on the free control space (e.g. in a ListBox).
/// </summary>
public static readonly DependencyProperty DragDirectlySelectedOnlyProperty
    = DependencyProperty.RegisterAttached("DragDirectlySelectedOnly",
                                          typeof(bool),
                                          typeof(DragDrop),
                                          new PropertyMetadata(false));
```

**Comment by petrnymsa** [comment]
@punker76 Thank you, it works now
