### ISSUE TITLE
Dragging an element as a child to an empty treeview item does not work

### ISSUE THREAD

**Issue by punker76** [punker76/gong-wpf-dragdrop#31]
_Original author: gmcnic...@gmail.com (February 18, 2011 19:21:53)_

Dropping a child element into a treeviewitem will not add the element as a child of the treeviewitem.

Take the default sample application, look at the 'bound treeview' window and drag all of the children from one parent to another, then once empty, try to drag one of the children back to the original parent.

_Original issue: http://code.google.com/p/gong-wpf-dragdrop/issues/detail?id=31_

**Comment by Toprakete** [comment]
Hi,
is there a solution now? With 1.0 Alpha I have already the same problem.
Thx and best reagrds
Klaus

**Comment by AnnekeHeelsum** [comment]
No unfortunately there isn't. My WPF knowledge is insufficient for this and noone else solved it. Sorry, Anneke


Date: Thu, 2 Apr 2015 05:15:03 -0700
