### ISSUE TITLE
Drop Event not Firing

### ISSUE THREAD

**Issue by RayBowman2017b** [punker76/gong-wpf-dragdrop#310]
## What steps will reproduce this issue?

Hi,

I'm having trouble catching the drop event. This is with a very simple example
reordering items in a ListBox.

The code is originally from a post to CodeProject:
    https://www.codeproject.com/Tips/805035/%2FTips%2F805035%2FReorder-DataGrid-ListBox-Items-with-Drag-and-Drop

I've pushed my own code to GitHub:
https://github.com/RayBowman2017b/WPF_DragDrop_ListBox_Example_01

When I set a breakpoint on the handlers that I've defined in code,
they are not hit.

### Expected outcome

Breakpoint to be hit while debugging with Visual Studio 2017 Community

### Repo

https://github.com/RayBowman2017b/WPF_DragDrop_ListBox_Example_01

### Environment

- GongSolutions.WPF.DragDrop 1.1.0
- Windows OS 10 pro 1803
- Visual Studio 2017
- .NET Framework 4.5

**Comment by punker76** [comment]
@RayBowman2017b You derived your [MainViewModel](https://github.com/RayBowman2017b/WPF_DragDrop_ListBox_Example_01/blob/master/Reorder_item_WPF/MainViewModel.cs#L13) from the IDropTarget to use it as the DropHandler, but you did not set this correct to the property.

https://github.com/RayBowman2017b/WPF_DragDrop_ListBox_Example_01/blob/master/Reorder_item_WPF/MainWindow.xaml#L10

This should fix your issue

```
dd:DragDrop.DropHandler="{Binding}"
```
