### ISSUE TITLE
怎么降低版本适合VS2017, .net core 2.19 , .net framework 4.5 也能运行

### ISSUE THREAD

**Issue by wangzhibinhttp** [punker76/gong-wpf-dragdrop#316]
怎么降低版本适合VS2017, .net core 2.19 , .net framework 4.5 也能运行

**Comment by punker76** [comment]
@wangzhibinhttp Please ask your question in English. Thx

**Comment by wangzhibinhttp** [comment]
How to lower the version for VS2017,.net core 2.19,.net framework 4.5 can also run.sorry

**Comment by wangzhibinhttp** [comment]
Run on a lower version

**Comment by punker76** [comment]
@wangzhibinhttp You can use this library (via NuGet) with .Net4.5 and higher and also with .Net Core 3.0 Preview 3. You can use VS 2015 to VS 2019. If you want to compile this repository then you must use VS 2019.
