### ISSUE TITLE
If a message box appears when you start dragging a file, mouse operations are disabled

### ISSUE THREAD

**Issue by p4j4dyxcry** [punker76/gong-wpf-dragdrop#317]
## What steps will reproduce this issue?

If a message box appears when you start dragging a file, mouse operations are disabled.

As a result of investigation, the cause that occurs seems to be due to two factors.
1. Values are set to IDragIndo.Data and IDragInfo.Effects
2. Delay the display of MessageBox

--- 

#### Problematic image
![error-image](https://user-images.githubusercontent.com/11988607/56563160-f5f68200-65e5-11e9-94c4-110e1506d012.gif)

### Expected outcome
The cursor expects a normal condition.

### Repo

Project file where the problem occurs.
[WpfApp2.zip](https://github.com/punker76/gong-wpf-dragdrop/files/3106348/WpfApp2.zip)

### Environment

- GongSolutions.WPF.DragDrop __v2.03__
- Windows OS __10__
- Visual Studio __2017__
- .NET Framework __4.6.1__

**Comment by punker76** [comment]
@p4j4dyxcry A message box is a modal window with a result which needs user interaction. So why do you need to show a message box at the start drag operation?

**Comment by p4j4dyxcry** [comment]
It's a complicated cause.  I am trying to decode data asynchronously at the start of dragging, but an error dialog may be displayed.  However, the error dialog can not be closed.  Because the project is huge, I prepared minimal data.

**Comment by punker76** [comment]
@p4j4dyxcry The start dragging (method) is not a good place to do such an operation. If you don't need the result at the start then it would be better to do this at the drag finished method.

**Comment by p4j4dyxcry** [comment]
In this use case, it is necessary to preview the 3D model while dragging.  So I had to decode and create a preview when I started dragging.
