### ISSUE TITLE
Treeview Scrolls Selction into view on Expand when using GongDD

### ISSUE THREAD

**Issue by jogibear9988** [punker76/gong-wpf-dragdrop#319]
## What steps will reproduce this issue?

I've a TreeView to wich I added GongDD like this:

 dd:DragDrop.IsDragSource="True" dd:DragDrop.IsDropTarget="True" 
            dd:DragDrop.UseDefaultDragAdorner="True"

While this is active, the Treeview will always scroll the selected Item into view when I expand a item.
This happend sicnce I've updated GongDD a few weeks ago

### Expected outcome

Treeview does not scroll

**Comment by jogibear9988** [comment]
I'm looking to debug the issue today, because I could not reproduce it with your sample app.

**Comment by jogibear9988** [comment]
It's because of this line:

https://github.com/punker76/gong-wpf-dragdrop/blob/a28e779a3441e4f94af7c0321616dc8f1634f1bf/src/GongSolutions.WPF.DragDrop/DragDrop.cs#L316

If I remove it, it works like before.

Can we introduce a setting for it?

**Comment by jogibear9988** [comment]
@punker76 
why was this introduced?

**Comment by jogibear9988** [comment]
https://github.com/punker76/gong-wpf-dragdrop/commit/9d7e694d115c8b911d60c8a3536fd1d218cbf4ee

**Comment by punker76** [comment]
@jogibear9988 it was introduced by #235 and #239

**Comment by jogibear9988** [comment]
what can we do?

**Comment by jogibear9988** [comment]
In a big Treeview with different levels, expaning on level alawys jumps around.

**Comment by punker76** [comment]
@jogibear9988 I will look for a solution. Maybe setting the focus only makes sense if the visual is a multi selection control.

**Comment by jogibear9988** [comment]
thx. as for now the user experience of my software is bad with this bug ;-)

**Comment by jogibear9988** [comment]
@punker76 do you have an estimate when this will be fixed?

**Comment by punker76** [comment]
@jogibear9988 Maybe this week

**Comment by jogibear9988** [comment]
@punker76 
if you only want the focus function to work on multiselector, then it will be only used in datagrid, listbox is also not a multiselctor control

**Comment by jogibear9988** [comment]
why should we scroll to the selected item on mouseevent?

**Comment by jogibear9988** [comment]
any news?

**Comment by punker76** [comment]
@jogibear9988  this has now been fixed, and it will be released in the next version

**Comment by jogibear9988** [comment]
Thanks, will test it!
