### ISSUE TITLE
Partially not working with custom ListView ControlTemplate

### ISSUE THREAD

**Issue by silviubogan** [punker76/gong-wpf-dragdrop#331]
## What steps will reproduce this issue?

1. Clone the repo linked to below.
2. Open the project in the repo in Visual Studio and restore NuGet packages.
3. Start debugging.
4. Try to drag an item that is not in the last position in the ListView, over the space that is below the last item in the ListView.
5. An interdiction mouse cursor is shown.

If I try to drop between two list items or near the first/last item in the ListView, everything works well. If I give the ItemsPresenter the name `ItemsPresenter`, as suggested [in the .NET docs](https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/listview-styles-and-templates), it still does not work.

### Screenshot

![wpf-gong-drag-drop-test-1_2019-09-15_18-08-25](https://user-images.githubusercontent.com/198924/64944167-67292100-d876-11e9-98a8-579140e5c323.png)

### Expected outcome

To be able to drop an item in the empty space below the last item in the ListView.

### Repo

https://github.com/silviubogan/wpf-gong-drag-drop-test-1

### Environment

I have tested this with the **latest commit on `master`** as of the moment of this writing: bf73cb4. I use the latest stable version of this library from NuGet in my actual project (**v2.0.6**). I use **VS 2019 Community** w/ the latest updates and **Win10 Pro** w/ the latest updates (1903).

In my actual project I use **.NET Framework 4.7.2** but for testing with the master branch I used **.NET Core 3 Preview**.

- GongSolutions.WPF.DragDrop __v2.0.6__
- Windows OS __10 Pro 1903__
- Visual Studio __2019__
- .NET Framework __4.7__

I could try to solve this issue if you do not have time for this in the next few weeks.

Thank you. Your library is very useful and of high quality.

### The XAML for the rest of this message
*(there is no code-behind)*

```xaml
<Window x:Class="wpf_gong_drag_drop_test_1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:wpf_gong_drag_drop_test_1"
        xmlns:dd="urn:gong-wpf-dragdrop"
        mc:Ignorable="d"
        Title="MainWindow" Height="164.286" Width="308.929">
    <Grid>
        <ListView
            dd:DragDrop.IsDragSource="True"
            dd:DragDrop.IsDropTarget="True"
            dd:DragDrop.SelectDroppedItems="True"
            dd:DragDrop.UseDefaultDragAdorner="False"
            >
            <ListView.ItemsPanel>
                <ItemsPanelTemplate>
                    <WrapPanel IsItemsHost="True" HorizontalAlignment="Stretch"
                               VerticalAlignment="Stretch"/>
                </ItemsPanelTemplate>
            </ListView.ItemsPanel>
            <ListView.Template>
                <!-- w/o this the items go beyond the right margin of the ListView -->
                <ControlTemplate TargetType="ListView">
                    <ItemsPresenter HorizontalAlignment="Stretch" VerticalAlignment="Stretch"
                                       AllowDrop="True" x:Name="ItemsPresenter"></ItemsPresenter>
                </ControlTemplate>
            </ListView.Template>
            <ListViewItem>test 1</ListViewItem>
            <ListViewItem>test 2</ListViewItem>
            <ListViewItem>test 3</ListViewItem>
            <ListViewItem>test 4</ListViewItem>
            <ListViewItem>test 5</ListViewItem>
            <ListViewItem>test 6</ListViewItem>
            <ListViewItem>test 7</ListViewItem>
            <ListViewItem>test 8</ListViewItem>
            <ListViewItem>test 9</ListViewItem>
            <ListViewItem>test 10</ListViewItem>
        </ListView>
    </Grid>
</Window>
```

**Comment by punker76** [comment]
@silviubogan This is a little bit tricky with the inner WrapPanel. You already tried to fix this with the ItemsPresenter, but this breaks the DragDrop functionality. You can get the same fix when you use this one (which I also used in my demos). 

```
<ListView
    dd:DragDrop.IsDragSource="True"
    dd:DragDrop.IsDropTarget="True"
    dd:DragDrop.SelectDroppedItems="True"
    dd:DragDrop.UseDefaultDragAdorner="False"
    >

    <ListView.ItemsPanel>
        <ItemsPanelTemplate>
            <WrapPanel Width="{Binding (FrameworkElement.ActualWidth), RelativeSource={RelativeSource AncestorType=ScrollContentPresenter}}"
                       IsItemsHost="True"
                       HorizontalAlignment="Stretch"
                       VerticalAlignment="Stretch"/>
        </ItemsPanelTemplate>
    </ListView.ItemsPanel>

    <ListViewItem>test 1</ListViewItem>
    <ListViewItem>test 2</ListViewItem>
    <ListViewItem>test 3</ListViewItem>
    <ListViewItem>test 4</ListViewItem>
    <ListViewItem>test 5</ListViewItem>
    <ListViewItem>test 6</ListViewItem>
    <ListViewItem>test 7</ListViewItem>
    <ListViewItem>test 8</ListViewItem>
    <ListViewItem>test 9</ListViewItem>
    <ListViewItem>test 10</ListViewItem>
</ListView>
```

**Comment by silviubogan** [comment]
Your solution works for me. Thank you.
