### ISSUE TITLE
DragDrop.DropHandler when datagrid inside datagrid?

### ISSUE THREAD

**Issue by true-perfect-code** [punker76/gong-wpf-dragdrop#334]
Hi All,

I have a main datagrid and in a column of the datagrid I have inserted a new datagrid (sub-datagrid) again.
If I enable drag/drop in xaml, everything works perfectly. I can move the entries in sub datagrid  between rows. I can also move elements from an external datagrid to sub datagrid.

But my problem is that I don't want to move the elements from external datagrid, I want to copy them. This should work by activating DropHandler (dd:DragDrop.DropHandler="{Binding}").
Well, it seems as if this doesn't work with a Sub-datagrid?

If I enable drophandeler on the main datagrid then it works, but I can't use that because I don't want to insert the entries into the main datagrid but into the column where my sub datagrid is.

Can anyone help me here?

Thanks

**Comment by C00lzer0** [comment]
Hi,
couldn't you use DragOver from the example to identify the main datagrid?
`ExampleItemViewModel sourceItem = dropInfo.Data as ExampleItemViewModel;`
`ExampleItemViewModel targetItem = dropInfo.TargetItem as ExampleItemViewModel;`
`if (targetItem is YourMainDataGrid) { ... }`

a question on my part:
I know it's the wrong place but how did you get the DropHandler working? I know there is a small example but i am to stupid to understand it (a complete working example would be nice ^^).

**Comment by true-perfect-code** [comment]
Hi,

I use MVVM pattern. In my ViewModel I have the two methods (as in the example of Gong):
- DragOver
- Drop
In the method DragDrop I set the FlagsDropTargetAdorners.Highlight and dropInfo.Effects = DragDropEffects.Copy.

In the method Drop I program my own intelligence but you need to query the lists (and you do that exactly as shown in the example).

Your mistake is probably that you think everything will work by itself. Unfortunately this is not the case, you have to query the lists (which contain your data in the view) and then program the addition of new items yourself to make it work.

Or you can use the standard functionality by enabling DragDrop properties in XAML. Now then, for more complicated things like me, you have the problem with sublists. There is another problem, in standard mode the items moved are not copied. But in my program I want to offer the copy functionality and so I have to program it myself.

Regrads

**Comment by C00lzer0** [comment]
Hi,
thanks for your info.
It works now (i should program some intelligence for me :/) but my main problem was that DragOver nor Drop get called. Now they do ... *happy*. 
All i had to do was to set the view model to the DataContext not the window itself (feeling dump oO).

**Comment by true-perfect-code** [comment]
Thanks
