### ISSUE TITLE
How to execute a method after drop

### ISSUE THREAD

**Issue by jinkstao** [punker76/gong-wpf-dragdrop#337]
I want to rearrange items which involves an Index property inside to change. So I have to execute my own method after drag and drop. I cannot find example in samples.

**Comment by jizc** [comment]
You will need a drop handler. You can check out how to do it in the wiki: https://github.com/punker76/gong-wpf-dragdrop/wiki/Usage#adding-a-drop-handler

**Comment by punker76** [comment]
@jinkstao If you implement the `IDragSource` interface then you will noticed with this two methods

https://github.com/punker76/gong-wpf-dragdrop/blob/167f40b17515009592b60cf5cc7a0b5b76dca71d/src/GongSolutions.WPF.DragDrop/IDragSource.cs#L34

https://github.com/punker76/gong-wpf-dragdrop/blob/167f40b17515009592b60cf5cc7a0b5b76dca71d/src/GongSolutions.WPF.DragDrop/IDragSource.cs#L41

The `IDropTarget` interface has this end method

https://github.com/punker76/gong-wpf-dragdrop/blob/167f40b17515009592b60cf5cc7a0b5b76dca71d/src/GongSolutions.WPF.DragDrop/IDropTarget.cs#L25

**Comment by behiunforgiven** [comment]
adding a drop handler prevent the default behavior; Is there any working example?
