### ISSUE TITLE
Expected imports are missing

### ISSUE THREAD

**Issue by choppinnn** [punker76/gong-wpf-dragdrop#340]
Hi, this is my first time using GitHub.
i encountered a issue while trying to open your project solution and im wondering if you may know why.
i have .net 3.1 installed as well.
any help would be much appreciated.
thank you.

<img width="1920" alt="Error message" src="https://user-images.githubusercontent.com/59193009/71399374-5d297200-265e-11ea-880f-a1f009164546.png">

**Comment by jizc** [comment]
I think the issue may be that you're running Visual Studio 2017.

Only Visual Studio 2019 is supported for .NET 3.x.
You can find more detailed info about it here: https://dotnet.microsoft.com/download/dotnet-core/3.0

**Comment by choppinnn** [comment]
> I think the issue may be that you're running Visual Studio 2017.
> 
> Only Visual Studio 2019 is supported for .NET 3.x.
> You can find more detailed info about it here: https://dotnet.microsoft.com/download/dotnet-core/3.0
> 
> Welcome to GitHub btw! 😃 🎉

Thanks so much for your help :)
Merry Christmas to you.
