### ISSUE TITLE
ListView extended selection issue when DragDrop.IsDragSource="True"

### ISSUE THREAD

**Issue by ssteezens** [punker76/gong-wpf-dragdrop#342]
###  What steps will reproduce this issue?

1. Create a ListView with ListItems that have clickable content (such as a checkbox) and set the SelectionMode="Extended"
2. Set dd:DragDrop.IsDragSource="True"
3. Select multiple list items 
4. Release CTRL key and click a checkbox element within one of the selected items

### Expected outcome
ListItem selection should not change and clicked item's event should be handled.  Note that expected behavior occurs when dd:DragDrop.IsDragSource="False" or when you keep the CTRL key held.
![gong drag drop extended selection expected behavior](https://user-images.githubusercontent.com/9289907/75714236-54c26880-5c99-11ea-92a8-7cf218b9469b.gif)

### Actual outcome
Element within selected ListItem's clicked event isn't fired.  ListItem selection changes to the ListItem that holds the clicked element.
![gong drag drop extended selection issue](https://user-images.githubusercontent.com/9289907/75714258-61df5780-5c99-11ea-9641-d754edfb0df3.gif)

### Repo

https://github.com/ssteezens/gong-dragdrop-listview-selection-issue

### Environment

- GongSolutions.WPF.DragDrop 2.x.x
- Windows 10 1903
- Visual Studio 2019
- .NET Framework 4.7 || .Net Core 3.1

**Comment by ogiesen** [comment]
This seems to be a duplicate of #336. I also have yet another scenario that appears to be triggered by the same root cause:

### Steps:

1. Create a `ListView` with `IsDragSource="True"` and `SelectionMode="Multiple"`
1. Select multiple items by clicking on them
1. Try to unselect one of the already selected items by clicking on it again

### Expected:
Item gets unselected

### Actual:
Item stays selected and cannot be unselected with the mouse

### Cause:
https://github.com/punker76/gong-wpf-dragdrop/blob/450e5513364f240463872b3d81810556d8d1ada6/src/GongSolutions.WPF.DragDrop/DragDrop.cs#L333-L345

Before I started using Gong DnD, I solved the problem mentioned in the source comment by postponing the initiation of the drag (via `DragDrop.DoDragDrop()`) until the mouse had moved by at least `SystemParameters.MinimumHorizontalDragDistance`/`MinimumVerticalDragDistance` since the `MouseDown`. Not yet sure how to apply this here.

**Comment by punker76** [comment]
@ssteezens You can prevent this by set DragSourceIgnore to true for the CheckBox and Menu

```xaml
<ListView ItemsSource="{Binding Items}" 
          dd:DragDrop.IsDragSource="True"
          SelectionMode="Extended">
    <ListView.ItemTemplate>
        <DataTemplate>
            <StackPanel Orientation="Horizontal">
                <CheckBox dd:DragDrop.DragSourceIgnore="True" />

                <TextBlock Text="Item 1" />

                <Menu dd:DragDrop.DragSourceIgnore="True">
                    <MenuItem Header="Menu">
                        <MenuItem Header="Some Menu Item"></MenuItem>
                        <MenuItem Header="Some Other Menu Item"></MenuItem>
                    </MenuItem>
                </Menu>
            </StackPanel>
        </DataTemplate>
    </ListView.ItemTemplate>
</ListView>
```

**Comment by punker76** [comment]
> This seems to be a duplicate of #336. I also have yet another scenario that appears to be triggered by the same root cause:
> 
> ### Steps:
> 1. Create a `ListView` with `IsDragSource="True"` and `SelectionMode="Multiple"`
> 2. Select multiple items by clicking on them
> 3. Try to unselect one of the already selected items by clicking on it again
> 
> ### Expected:
> Item gets unselected
> 
> ### Actual:
> Item stays selected and cannot be unselected with the mouse
> 
> ### Probable Cause:
> https://github.com/punker76/gong-wpf-dragdrop/blob/450e5513364f240463872b3d81810556d8d1ada6/src/GongSolutions.WPF.DragDrop/DragDrop.cs#L333-L345
> 
> Before I started using Gong DnD, I solved the problem mentioned in the source comment by postponing the initiation of the drag (via `DragDrop.DoDragDrop()`) until the mouse had moved by at least `SystemParameters.MinimumHorizontalDragDistance`/`MinimumVerticalDragDistance` since the `MouseDown`. Not yet sure how to apply this here.
> 
> ### Environment:
> * GongSolutions.WPF.DragDrop 2.2.0
> * Windows 10 1909
> * Visual Studio 2019
> * .NET Framework 4.6.2

@ogiesen It's a bug with the SelectionMode Multiple which [is fixed](https://github.com/punker76/gong-wpf-dragdrop/pull/365/commits/d042c5721404d52dde6bc192b66fcb15a6e3574d) now and will be available with v2.4.0

**Comment by ssteezens** [comment]
@punker76 Awesome, thank you!

**Comment by jimfoye** [comment]
@punker76 Do you think we will have the 2.4.0 release soon?
