### ISSUE TITLE
TreeView insert index is wrong when item can't have children

### ISSUE THREAD

**Issue by jizc** [punker76/gong-wpf-dragdrop#344]
## What steps will reproduce this issue?

I have a tree view where some items are containers and others are not. When dragging an item onto a non-container, the library still assumes I want to add the item as a child of the target. This causes the target collection and the insert index in the drop info to not be what I need. I can't find a built-in way of handling this issue. The sample repo below demonstrates the issue.

![TreeViewIssue](https://user-images.githubusercontent.com/1404846/76632113-f8860100-6542-11ea-880d-4f31fe6579ec.gif)

### Expected outcome

I need a way to tell the library that a tree view item should not be considered a valid parent, so that non-container items can be inserted as siblings.

I have a working solution that I will submit as a PR. I'm very open to solving this in a different way if anyone has a better idea! 😃 

### Repo

https://github.com/jizc/gong-wpf-dragdrop-treeview-issue

### Environment

- GongSolutions.WPF.DragDrop __v2.2.0__
- Windows OS __10__
- Visual Studio __2019__
- .NET Framework __4.6.2__ / .NET Core __3.1__

**Comment by SpoinkyNL** [comment]
@punker76 any chance this could be addressed? It would be great to have a solution for this.

**Comment by jizc** [comment]
I'm closing this as I'm currently working on a new fork that will address this and some other niche issues we have in our project.

**Comment by punker76** [comment]
@jizc And why not here?

**Comment by jizc** [comment]
If my current plan works and I can do it in a clean enough way, I'll submit a new PR. Right now I just need to get it working in our project, so it might be a little messy at first 😅
