### ISSUE TITLE
Patch: DragInfofactory

### ISSUE THREAD

**Issue by punker76** [punker76/gong-wpf-dragdrop#36]
_Original author: a...@chambills.com (May 25, 2011 10:14:22)_

Linked to issue 26, but with a complete patch.

Not sure what your final plans are.
But we are needing to drag items from controls which are not item controls.
such as DevExpress Grids, Images etc

At the moment the DragInfo was tightly couple to the Drag Source being ItemsControl.

This patch abstracts the creation of DragInfo behind a factory allowing for other IDragInfo to be created.

Factory can be set like the handler via dependency property

_Original issue: http://code.google.com/p/gong-wpf-dragdrop/issues/detail?id=36_

**Comment by jrgcubano** [comment]
I'm facing this same problem with a custom grid to allow drag and drop between rows!.

Implementing a factory sounds like a good option right now, so does not introduce any breaking change.
