### ISSUE TITLE
if list has duplicates, result is in unexpected order

### ISSUE THREAD

**Issue by bradwbradw** [punker76/gong-wpf-dragdrop#397]
**Describe the bug**
If a list has multiple objects that are identical, then the library does not work as expected. Dragging produces an incorrect order.

**To Reproduce**
Start with a list with some identical objects, for example: `A,B,A`
Drag the second A to go to the very start of the list.

**Expected behavior**
The resulting list should be `A,A,B`, but it's actually still `A,B,A`

Using library version 2.4.1.

**Additional context**
I found the reason for the bug, it's because `Drop(IDropInfo dropInfo)` is using `IndexOf` to find the item being dragged.  So the problem is that it believes that the first A was dragged, because IndexOf defaults to the first instance it finds if there are multiple identical objects.

I think a reasonable solution is just to instead look at `dropInfo.DragInfo.SourceIndex` to find the object that should move to a new position.

**Comment by punker76** [comment]
@bradwbradw Drag&Drop operations on a list which can contains duplicate items is not so easy at first glance. Because the library uses the IndexOf method to get the correct index of the dragged items. Your solution may work with only one item, but not with multiple one. So my solution/suggestion is to put your values in a proxy object and work with this. I tested this with strings, so maybe it will not work for you.

Here is the proxy class

```csharp
public class DragDropObjectModel<T>
{
    public DragDropObjectModel(T aValue)
    {
        this.Value = aValue;
    }

    public T Value { get; }

    public override string ToString()
    {
        return this.Value.ToString();
    }
}
```

and here the usage in my sample app

```csharp
public ObservableCollection<DragDropObjectModel<string>> Collection5 { get; set; } = new(new[] { "A", "B", "A", "A", "A", "B" }.Select(x => new DragDropObjectModel<string>(x)));

public ObservableCollection<DragDropObjectModel<string>> Collection6 { get; set; } = new();
```

```xaml
<Grid>
    <Grid.ColumnDefinitions>
        <ColumnDefinition Width="*" />
        <ColumnDefinition Width="*" />
    </Grid.ColumnDefinitions>

    <ListBox x:Name="LeftBoundListBox"
             Grid.Column="0"
             dd:DragDrop.CanDragWithMouseRightButton="True"
             dd:DragDrop.DropTargetAdornerBrush="Coral"
             dd:DragDrop.IsDragSource="True"
             dd:DragDrop.IsDropTarget="True"
             dd:DragDrop.UseDefaultEffectDataTemplate="True"
             ItemsSource="{Binding Data.Collection5}" />
    <ListBox x:Name="RightBoundListBox"
             Grid.Column="1"
             dd:DragDrop.DropTargetAdornerBrush="Coral"
             dd:DragDrop.IsDragSource="True"
             dd:DragDrop.IsDropTarget="True"
             dd:DragDrop.ShowAlwaysDropTargetAdorner="True"
             ItemsSource="{Binding Data.Collection6}" />
</Grid>
```

**Comment by bradwbradw** [comment]
Thanks

I ended up just wrapping my object in a container class, which are unique, so pretty similar to what you suggested.

I tried to override your lib and replace IndexOf with using DragInfo's value, but then I got problems trying to drag multiple items.  It would behave differently depending on which single item out of the selected set I clicked on to drag

If I were writing this lib, I would consolide the code so that dragging arrays and single objects use the exact same code path, so single objects are represented as an array with one object. I'd pass an array of selected indeces in `DragInfo` and use that instead of IndexOf, cause it's closer to the truth.  Why even pass an index in DragInfo if it's just going to use IndexOf anyway?  I think single objects, arrays, duplicates, uniques would all behave consistently with that change.

That's just me though.  Thanks for the lib!

**Comment by punker76** [comment]
> Thanks
> 
> I ended up just wrapping my object in a container class, which are unique, so pretty similar to what you suggested.
> 
> I tried to override your lib and replace IndexOf with using DragInfo's value, but then I got problems trying to drag multiple items. It would behave differently depending on which single item out of the selected set I clicked on to drag
> 

Yes, that's exactly the problem here.

> If I were writing this lib, I would consolide the code so that dragging arrays and single objects use the exact same code path, so single objects are represented as an array with one object. I'd pass an array of selected indeces in `DragInfo` and use that instead of IndexOf, cause it's closer to the truth.

This is exactly the kind of solution I had in mind. But this can't be implemented this way, because an ItemsControl can also have a filtered list and then the indices in the view don't match the one in the collection. So you have to work with IndexOf in the original collection.

> Why even pass an index in DragInfo if it's just going to use IndexOf anyway? I think single objects, arrays, duplicates, uniques would all behave consistently with that change.
> 

Yes, that's correct, but not so easy to implement. In most cases the IndexOf works because you have unique items.

> That's just me though. Thanks for the lib!

Thank you! 🙏🏻
