### ISSUE TITLE
Move only

### ISSUE THREAD

**Issue by punker76** [punker76/gong-wpf-dragdrop#4]
_Original author: kovm...@gmail.com (January 14, 2010 20:42:43)_

I really appreciate what you have done. I would like to use your project, but 
I haven't found the way how to only move items. Copy is no use for me.

Is it a unknown feature, or future feature, or not featured at all?

_Original issue: http://code.google.com/p/gong-wpf-dragdrop/issues/detail?id=4_

**Comment by JobaDiniz** [comment]
Hi, there's no **Remove** method on `dropInfo.DragInfo.SourceCollection.Remove(item)`

How can I remove the item from the source collection?
