### ISSUE TITLE
Select items from bottom to top

### ISSUE THREAD

**Issue by AlexNoBadMan** [punker76/gong-wpf-dragdrop#400]
**Describe the bug**
If you start selecting items from bottom to top, then after inserting, the bottom item will be at the top. Apparently this is the specific behavior of the SelectedItems property.

**To Reproduce**
Select items from bottom to top and drop.

**Expected behavior**
Items must be inserted in the standard order.

**Screenshots**
![orderbug](https://user-images.githubusercontent.com/39050462/134721464-6029d9c1-c970-4148-ae24-98d64dd7f671.gif)

**Environment**
 - GongSolutions.WPF.DragDrop 2.4.2
 - OS: Windows 10
 - Visual Studio 2019
 - .NET Framework 4.8

**Additional context**
I solved the problem as follows:
in the Drop method after ExtractData, add the following code:

var data = ExtractData(dropInfo.Data).OfType<object>().ToList();
if (data.Count > 1 && destinationList.IndexOf(data[0]) > destinationList.IndexOf(data[1]))
{
    var removedItem = data[0];
    data.RemoveAt(0);
    data.Insert(data.Count - 1, removedItem);
}

You may be able to find a better solution.

**Comment by punker76** [comment]
@AlexNoBadMan This is not a bug, this is the normal selection behavior of the SelectedItems property. But you can sort the items in your own way with the `DragPreviewItemsSorter` and/or `DropTargetItemsSorter` property and the `IDragPreviewItemsSorter` and `IDropTargetItemsSorter` interfaces.

Here is an example:

https://github.com/punker76/gong-wpf-dragdrop/blob/d5deb8e5c3be00d105785a9b7bf32a2ae278847b/src/Showcase/Views/MixedSamples.xaml#L41-L76

and

https://github.com/punker76/gong-wpf-dragdrop/blob/d5deb8e5c3be00d105785a9b7bf32a2ae278847b/src/Showcase/ViewModels/MainViewModel.cs#L146-L162
