### ISSUE TITLE
Events to notify when dragging over a non-droppable region

### ISSUE THREAD

**Issue by sfmc** [punker76/gong-wpf-dragdrop#402]
## Add functionality to notify user when actively dragging over a non-droppable region.

This feature could be useful for situations when the user wants to update their VMs with custom behaviors such as:
* Notifying IDropTarget when dragging operation has dragged off the potential DropTarget
* Updating custom IDragInfo.Data object based on active drop target. For example, to copy the behavior of one-drive when "File A" is dragged over "Folder B", the DragAdorner tooltip changes to "File A to Folder B"

Possible new functions could be:
* IDropTarget.DragLeave()
* IDragSource.DraggedOverNonDroppableRegion()

Thanks for your consideration and help!

**Comment by sfmc** [comment]
Amazing, excited to try this out!

**Comment by giesen-ascora** [comment]
BTW: this was a breaking change... (as noted in the MR) Any hints on how to implement `IDropTarget.DragEnter()` and `DragLeave()` on my target VM? Can/should I just leave them empty?
