### ISSUE TITLE
Adorner effect when drag over custom template

### ISSUE THREAD

**Issue by Antastsy7** [punker76/gong-wpf-dragdrop#416]
I have a custom listview template that contains several line of text like below
![dragover](https://user-images.githubusercontent.com/22287325/142735865-ee017e9a-6a5e-4ff4-a301-d7e7725d0c12.gif)

However, the adorned effect is shown only if my cursor is not overlapping these text. Is there any way to make the adorner effect be always shown? I tried ShowAlwaysDropTargetAdorner but seems not work

**Comment by punker76** [comment]
@Antastsy7 It would be nice if you can show the ListView/ListViewItem template. And how you do the drag&drop operation. Maybe you can make a simple app which reproduces this issue. With this it's then easier to debug and understand this. Thx

**Comment by Antastsy7** [comment]
Here is my template

**Comment by Antastsy7** [comment]
![image](https://user-images.githubusercontent.com/22287325/142745103-e52ea1e0-aefa-4de3-abef-3e38c314c7cb.png)
Here is my template, just a stackpanel with some textboxs

**Comment by Antastsy7** [comment]
https://github.com/Antastsy7/dragdropdemo
Just did a sample for this, while I drag the item from left to right listbox, if the item is overlap with contents on it, the adorner effect does not show.

**Comment by punker76** [comment]
@Antastsy7 Thx for the sample! You have 2 options to get this working, because the TextBox allows hit testing:

First you can try useing `dd:DragDrop.DropEventType="Tunneled"` on the target ListBox

```xaml
<ListBox 
    Grid.Column="1"
    ItemsSource="{Binding CustomDatas}"
    dd:DragDrop.IsDropTarget="True"
    dd:DragDrop.DropEventType="Tunneled"
    dd:DragDrop.ShowAlwaysDropTargetAdorner="True"
    dd:DragDrop.UseDefaultDragAdorner="True"
    dd:DragDrop.DropHandler="{Binding}"
    >
    <ListBox.ItemTemplate>
        <DataTemplate>
            <StackPanel>
                <TextBox Text="{Binding Name}" />
                <TextBox Text="{Binding Description}" />
            </StackPanel>
        </DataTemplate>
    </ListBox.ItemTemplate>
</ListBox>
```

Or you can set `IsHitTestVisible="False"`

```xaml
<ListBox 
    Grid.Column="1"
    ItemsSource="{Binding CustomDatas}"
    dd:DragDrop.IsDropTarget="True"
    dd:DragDrop.ShowAlwaysDropTargetAdorner="True"
    dd:DragDrop.UseDefaultDragAdorner="True"
    dd:DragDrop.DropHandler="{Binding}"
    >
    <ListBox.ItemTemplate>
        <DataTemplate>
            <StackPanel IsHitTestVisible="False">
                <TextBox IsHitTestVisible="False" Text="{Binding Name}" />
                <TextBox Text="{Binding Description}" />
            </StackPanel>
        </DataTemplate>
    </ListBox.ItemTemplate>
</ListBox>
```

![gong_target_adorner](https://user-images.githubusercontent.com/658431/142758447-a26032d0-ef7f-40d6-ac8d-009b66a88702.gif)

**Comment by Antastsy7** [comment]
oh right that works perfectly!!! thanks so much!!!!!!!!!!!!!!!
