### ISSUE TITLE
Drag&Drop on a touch device

### ISSUE THREAD

**Issue by KKauK** [punker76/gong-wpf-dragdrop#418]
Trying to drag an item on a touch screen causes the mouse pointer to freeze for seconds and follow up the fingeer at random intervals. Please see the attached video sequence where the blue rectangle shows the current behaviour while the red rectangle shows the desired way.
The same operations show no problems if only the mouse pointer is used.

https://user-images.githubusercontent.com/7251838/142870991-389bcbff-ddc1-45e4-82c0-c4ef780a5196.mp4

The problem seems to be caused by the SetWindowsHookEx in MouseHelper.cs

Attached is a fix for the problem based on the current sources. The fix uses a System.Windows.Threading.DispatcherTimer instead of the hook and can be activated by setting a new "MouseMoveTimerTriggered" attached property.

Please have a  look a the modifications. It would be great if you could add them to you project.

I really apprechiate your work!!

[DraDropTouch.zip](https://github.com/punker76/gong-wpf-dragdrop/files/7581788/DraDropTouch.zip)

**Comment by GioviQ** [comment]
I experience the same issue.

**Comment by KKauK** [comment]
Hey @punker76, I really love your work and I know that you are doing all this on a voluntary base. But I have to ask if you had any chance to look a this issue or if you see any chance for the upcoming future?

**Comment by punker76** [comment]
@KKauK I have maybe the chance in the next weeks to test this with a physical touch device.

**Comment by KKauK** [comment]
@punker76 That sounds great;-). Just drop me a note if you need more information / support.
