### ISSUE TITLE
Regression: Drag of Button broken since 2.4

### ISSUE THREAD

**Issue by nzain** [punker76/gong-wpf-dragdrop#420]
**Describe the bug**
We use your library with great success for many years (thanks!) with a large `TreeView` structure, where nodes of various types can be dragged & dropped within the tree. Some of the draggable nodes are buttons too: simple click executes the command, click+drag will move the node to another place. This has been working for us up to version 2.3.2. However, it does not work in version 2.4 or 2.4.3 (I didn't test others in between). All other drag&drop operations seem to work just fine, only buttons seem to eat the event.

When adding a large `Margin="20"` the margin-part of the node can be dragged as usual. Dragging the inner button visual does not fire the drag operation. Going back to 2.3.2 restores the functionality. Looking through the release notes, I don't see anything suspicious. Did I miss something?

**To Reproduce**
1. Try to drag a treeview element composed of a button

**Expected behavior**
The drag event is fired.

**Desktop (please complete the following information):**
 - OS: windows 10 (21H1)
 - .Net Framework 4.8

**Comment by punker76** [comment]
@nzain @Difference I found the change which causes this new issue. I added ToggleButton controls to the hit testing method which check for non dragging action (#342). I have fixed this now in #421. The new v3.0.0 will be released soon. Thx

**Comment by nzain** [comment]
@punker76 thanks for the very fast fix! Tested with 3.0.0, looks good.

**Comment by Difference** [comment]
@punker76 Same here : thanks for the very fast fix! Tested with 3.0.0, looks good.
