### ISSUE TITLE
Right-click while dragging causes drag adorner to remain shown

### ISSUE THREAD

**Issue by gtaylor1981** [punker76/gong-wpf-dragdrop#425]
If the mouse is right-clicked while dragging, the drag adorner remains visible (on top of all other desktop windows) until a new drag is started.
I would expect the click to cancel the drag at least, and potentially open a context menu (i.e. pass through the event to the underlying control).

To reproduce:
1. Drag any item with a drag adorner
2. Right-click mouse while still dragging

Seen on Win10 1909 in Showcase.WPF.DragDrop.exe
Can also reproduce by clicking mouse wheel.

Note: if 'CanDragWithMouseRightButton' selected, then clicking the left-button also causes this bug.

**Comment by jizc** [comment]
Thank you for this info! I've have users of our app complain about adorners that don't go away, but I haven't been able to reproduce it. I'll look into making a fix sometime this week.
