### ISSUE TITLE
It seems that DropHandler and DragHandler are not working together when both set

### ISSUE THREAD

**Issue by lmuestak** [punker76/gong-wpf-dragdrop#428]
**Introduction**
I have the following interface which also implements the <code>IDropTarget</code>and <code>IDragSource</code>.

<pre>
    public interface IFolderBrowserViewModel : IViewModelBase, IDragSource, IDropTarget
    {
        ...
    }
</pre>

There is also a corresponding class called <code>FolderBrowserViewModel</code> which implements the <code>IFolderBrowserViewModel</code> interface.

<pre>
    public class FolderBrowserViewModel: ViewModelbase, IFolderBrowserViewModel
   {
        ...

        public void DragOver(IDropInfo dropInfo)
        {
            ...

        }

        public void Drop(IDropInfo dropInfo)
        {
            ...
        }

        public void Dropped(IDropInfo dropInfo){  }

        public void StartDrag(IDragInfo dragInfo)
        {
            //if (dragInfo.VisualSource is TreeView || dragInfo.VisualSource is TreeViewItem)
            //{
            //    Debug.WriteLine($"Drag source is TreeView/TreeViewItem {dragInfo.SourceItem}");
            //}
        }

        public bool CanStartDrag(IDragInfo dragInfo)
        {
            return true;
        }

        public void DragDropOperationFinished(DragDropEffects operationResult, IDragInfo dragInfo){  }
        public void DragCancelled(){  }

        public bool TryCatchOccurredException(Exception exception)
        {
            return true;
        }

   }
</pre>

The user control <code>FolderBrowserView</code> I'm using is containing a <code>TreeView</code> element with the following configuration:

<pre>

&lt;TreeView 
        dd:DragDrop.IsDragSource="True"
        dd:DragDrop.IsDropTarget="True"
        dd:DragDrop.DragAdornerTemplate="{StaticResource FolderDragAdorner}"
        dd:DragDrop.SelectDroppedItems="True"
        dd:DragDrop.DropHandler="{Binding}"
        dd:DragDrop.DragHandler="{Binding}"
        dd:DragDrop.DropTargetAdornerBrush="LightSkyBlue"
        dd:DragDrop.DragDirectlySelectedOnly="True"&gt;
      ...
&lt;/TreeView&gt;
</pre>

**The issue**

If only one of the properties is set then the drag and drop seems to work.
<pre>
&lt;TreeView 
...
dd:DragDrop.DropHandler="{Binding}"&gt;
...
&lt;/TreeView&gt;
</pre>
or like
<pre>
&lt;TreeView 
...
dd:DragDrop.DragHandler="{Binding}"&gt;
...
&lt;/TreeView&gt;
</pre>

But if I set both properties then nothing works.
<pre>
&lt;TreeView 
...
dd:DragDrop.DropHandler="{Binding}"
dd:DragDrop.DragHandler="{Binding}"&gt;
...
&lt;/TreeView&gt;
</pre>
Any ideas what the problem is?

**Comment by punker76** [comment]
@lmuestak I tried to reproduce this with the following code. But I don't  see an issue here. Is there maybe some other code not working or an exception thrown?

```csharp
    public interface IDragDropHandler : IDragSource, IDropTarget
    {
    }

    public class MainViewModel : ViewModelBase, IDragDropHandler
    {
        public void StartDrag(IDragInfo dragInfo)
        {
            GongSolutions.Wpf.DragDrop.DragDrop.DefaultDragHandler.StartDrag(dragInfo);
        }

        public bool CanStartDrag(IDragInfo dragInfo)
        {
            return GongSolutions.Wpf.DragDrop.DragDrop.DefaultDragHandler.CanStartDrag(dragInfo);
        }

        public void Dropped(IDropInfo dropInfo)
        {
            GongSolutions.Wpf.DragDrop.DragDrop.DefaultDragHandler.Dropped(dropInfo);
        }

        public void DragDropOperationFinished(DragDropEffects operationResult, IDragInfo dragInfo)
        {
            GongSolutions.Wpf.DragDrop.DragDrop.DefaultDragHandler.DragDropOperationFinished(operationResult, dragInfo);
        }

        public void DragCancelled()
        {
        }

        public bool TryCatchOccurredException(Exception exception)
        {
            return false;
        }

        public void DragEnter(IDropInfo dropInfo)
        {
            GongSolutions.Wpf.DragDrop.DragDrop.DefaultDropHandler.DragEnter(dropInfo);
        }

        public void DragOver(IDropInfo dropInfo)
        {
            GongSolutions.Wpf.DragDrop.DragDrop.DefaultDropHandler.DragOver(dropInfo);
        }

        public void DragLeave(IDropInfo dropInfo)
        {
            GongSolutions.Wpf.DragDrop.DragDrop.DefaultDropHandler.DragLeave(dropInfo);
        }

        public void Drop(IDropInfo dropInfo)
        {
            GongSolutions.Wpf.DragDrop.DragDrop.DefaultDropHandler.Drop(dropInfo);
        }
    }
```

The binding is to the MainViewModel

```xaml
<TreeView dd:DragDrop.IsDragSource="True"
          dd:DragDrop.IsDropTarget="True"
          dd:DragDrop.DragHandler="{Binding}"
          dd:DragDrop.DropHandler="{Binding}"
          dd:DragDrop.UseDefaultDragAdorner="True"
          dd:DragDrop.UseDefaultEffectDataTemplate="True"
          dd:DragDrop.SelectDroppedItems="True"
          ItemsSource="{Binding Data.TreeCollection1}">
    <TreeView.ItemTemplate>
        <HierarchicalDataTemplate ItemsSource="{Binding Children}">
            <TextBlock Margin="2" Text="{Binding Caption}" />
        </HierarchicalDataTemplate>
    </TreeView.ItemTemplate>
</TreeView>
```

![gong_dragdrop_interface](https://user-images.githubusercontent.com/658431/151658789-73df0a46-913b-46e6-974a-6721fe4f3b0f.gif)

**Comment by lmuestak** [comment]
Hi @punker76,

Im not able to drag or drop when both are handlers are set (drag and drop adorners are not visible and not moving). And there is also not exception in code. My goal is to drag some items from the treeview or listview onto to windows explorer to copy them. if drophandler is set then im able drag and drop items between treeview/treeview treeview/listview or listview/listview. 

unfortunetly, im sitting so long an that issue.

Best regards

**Comment by punker76** [comment]
@lmuestak Thanks for the sample and clarifying the issue. If you want to do a file drop then you can use your own DataObject to set the SetFileDropList.

```csharp
        public void StartDrag(IDragInfo dragInfo)
        {
            // drag&drop inside the ListBox with control key
            if (Keyboard.Modifiers.HasFlag(ModifierKeys.Control))
            {
                GongSolutions.Wpf.DragDrop.DragDrop.DefaultDragHandler.StartDrag(dragInfo);
            }
            else
            {
                var files = dragInfo.SourceItems.OfType<FileModel>().Select(f => f.File).ToArray();

                var dataObject = new DataObject();
                var sc = new System.Collections.Specialized.StringCollection();
                sc.AddRange(files!);
                dataObject.SetFileDropList(sc);

                dragInfo.DataObject = dataObject;
                dragInfo.Effects = DragDropEffects.Copy;
            }
        }
```

I have created a full sample where you can drop files on and drag files to the explorer.

https://github.com/punker76/gong-wpf-dragdrop-file-sample

**Comment by lmuestak** [comment]
Hi @punker76,

thank you so much for help. Unfortunetly the link to your full example is not available.
https://github.com/punker76/gong-wpf-dragdrop-file-sample

![image](https://user-images.githubusercontent.com/3002593/151720150-0ac7be18-42d1-4aed-9998-08360acf0d5a.png)

Best regards

**Comment by punker76** [comment]
@lmuestak Sorry, it was private, it's now public.

**Comment by lmuestak** [comment]
Now, its available. Thanks a lot!

**Comment by punker76** [comment]
@lmuestak Can i close this issue now?

**Comment by lmuestak** [comment]
@punker76 Yes, thanks a lot!
