### ISSUE TITLE
DropHandlerExample link leads to a blanc page

### ISSUE THREAD

**Issue by dasha-ign** [punker76/gong-wpf-dragdrop#429]
**Describe the bug**
DropHandlerExample link leads to nowhere

**To Reproduce**
1. Go to 'https://github.com/punker76/gong-wpf-dragdrop/wiki/Usage'
2. Scroll down to the bottom of the page
3. Click on 'DropHandlerExample' link
4. See the empty page it leads to

**Expected behavior**
It would be great to have a working example to look at

**Screenshots**
00 - the first page screeshot
01 - the example page screenshot
![00](https://user-images.githubusercontent.com/9736811/150779021-12466ec4-ae36-425e-9baf-a239e5ad1f83.png)
![01](https://user-images.githubusercontent.com/9736811/150779026-7839d90c-261b-48c0-9d81-6d34183e154e.png)

**Comment by jizc** [comment]
I copied over the [Drop Handler Example](https://code.google.com/archive/p/gong-wpf-dragdrop/wikis/DropHandlerExample.wiki) from the Google Code Archive, so the [link](https://github.com/punker76/gong-wpf-dragdrop/wiki/Examples) works now.

It doesn't provide a ton more info than what's already on the Usage wiki page, but maybe it will be a bit helpful.
