### ISSUE TITLE
IDropTarget methods don't fire if using Gong drap/drop in an AvalonDock floating window

### ISSUE THREAD

**Issue by punker76** [punker76/gong-wpf-dragdrop#44]
_Original author: epalmite...@gmail.com (January 12, 2012 16:43:10)_

<b>What steps will reproduce the problem?</b>
1. Include AvalonDock and Gong DragDrop in a WPF project.
2. Create an AvalonDock DockingManager with a DockableContent pane.
3. Drag the DockableContent out as a floating window.
4. Attempt to drag/drop anything with Gong DragDrop in the floating window.

<b>What is the expected output? What do you see instead?</b>
The IDropTarget methods are never fired.

<b>What version of the product are you using? On what operating system?</b>
GongSolutions.Wpf.DragDrop-0.1.2.zip on Windows 7.

<b>Please provide any additional information below.</b>
To be honest, I'm not sure if this is a Gong problem or AvalonDock problem.  Just putting it out there that Gong DragDrop and AvalonDock don't play nice.  Note that everything works perfectly in a non-floating (docked) window.

_Original issue: http://code.google.com/p/gong-wpf-dragdrop/issues/detail?id=44_

**Comment by QuantumDeveloper** [comment]
@punker76 Any update to this issue?

**Comment by epalm** [comment]
Ditto.

**Comment by punker76** [comment]
I retested this with `Xceed.Wpf.AvalonDock` v3.1.16356.12170 and don't get this exception. It works perfectly :-D
