### ISSUE TITLE
Orientation priority handling in 2D lists or grids

### ISSUE THREAD

**Issue by hahagu** [punker76/gong-wpf-dragdrop#442]
**Describe the bug**
In a 2D list, such as [HandyControl](https://ghost1372.github.io/handycontrol/)'s [FlexPanel](https://ghost1372.github.io/handycontrol/extend_controls/flexPanel/), or the UniformGrid, the position of the adorner is set by the closest element. However, in some cases, it is preferable to make horizontal plane or vertical plane take priority in terms of closest-ness. 

For example,
![image](https://user-images.githubusercontent.com/3746349/169600135-442615ad-e10f-479c-b85d-50b24cf94634.png)
If a user were to drag and drop a control into the cursor position, it'd be preferrable for the control to be dropped next to p8 instead of where the adorner is now. However, this is not the behavior as of now.

Is there a way to do this currently? Thanks.

**To Reproduce**
1. Create a two-dimensional grid/list.
2. Attach the dragdrop handler.
3. Move a drag-droppable object around to see behavior.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 21H2

**Comment by punker76** [comment]
@hahagu You can implement your own drop target with the IDropTarget interface to place the dropped item always on the "last" position in the list.
