### ISSUE TITLE
DropTargetAdorners.Highlight has wrong location

### ISSUE THREAD

**Issue by RedX2501** [punker76/gong-wpf-dragdrop#449]
**Describe the bug**
When you have non-visible elements the Highlight border is misaligned.

**To Reproduce**

Open project, drag element onto target element.

[DragDropBugReport.zip](https://github.com/punker76/gong-wpf-dragdrop/files/9072969/DragDropBugReport.zip)

This project uses the latest version with .net 6 but I have the problem with .net framework 4.7.2.

**Expected behavior**
The highlight border should be around the gray element but is offset.

The computation of the size to highlight is correct but the offset is not.

**Desktop (please complete the following information):**
 - OS: Win 10

 - Version: DragDrop 3.1.1

**Additional context**

**Comment by RedX2501** [comment]
I do realize that a workaround exists by moving the dd:IsDropTarget to the border.

I do still think this is a problem since there is a code to calculate the accurate size of the target but the offset is not considered.

**Comment by punker76** [comment]
@RedX2501 The problem here was that the target UserControl doesn't set a Background brush (like Transparent) to use the entire bounds. So the result is then the wrong position for the inner bounds. Workaround is to set the Background, but I also fixed that now.
