### ISSUE TITLE
Functional Recommendations：ctrl+drag

### ISSUE THREAD

**Issue by DR-ShenSSR** [punker76/gong-wpf-dragdrop#478]
**Functional Recommendations**
Is there a ctrl+drag that allows copy insertion? I think this would be helpful for separate object manipulation, for example to help chapter catalogs to be built through existing templates

**Comment by DR-ShenSSR** [comment]
First of all thanks for the existence of such a great plugin.
I get conflicts with the program when I write the following code：
    Private Shared Sub StartDragDrop(row As DataGridRow)
        If row IsNot Nothing Then
            SetIsDragging(row, True)
            If Keyboard.IsKeyDown(Key.LeftCtrl) OrElse Keyboard.IsKeyDown(Key.RightShift) Then
                ' Hold Ctrl to drag and drop as copy and add the
                DragDrop.DoDragDrop(row, row.Item, DragDropEffects.Copy)
            End If
        End If
    End Sub

**Comment by punker76** [comment]
There is a clone sample in the main sample application https://github.com/punker76/gong-wpf-dragdrop/blob/e6daaf720d5a510ecf5b083e7770cc4eaa00f9a4/src/Showcase/Views/MixedSamples.xaml#L349-L401
