### ISSUE TITLE
Drag adorner freezes on screen after middle mouse button is pressed

### ISSUE THREAD

**Issue by RayCarrot** [punker76/gong-wpf-dragdrop#493]
**Describe the bug**
There appears to be a bug where the drag adorner can freeze in place on screen. The way I've been able to consistently reproduce it is by dragging an item, while holding down my left mouse button, and then pressing the middle mouse button.

**To Reproduce**
1. Go to the "Mixed" page in the showcase app
2. Drag any item with the left mouse button, and without letting go press the middle mouse button
3. The adorner is now stuck on screen and will even overlap other windows

**Expected behavior**
I expect the drag-drop operation to be fully canceled and the adorner to stop showing

**Screenshots**
![Showcase](https://github.com/punker76/gong-wpf-dragdrop/assets/33812678/b60558d3-b36a-4af7-af45-7df9feabdcf0)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 23H2

**Comment by VacuumBreather** [comment]
I can confirm this issue, and it happens in our project also under other circumstances, which we haven't been able to reliably reproduce yet, but seem to have the same core issue. State is not correctly reset on Drag Cancellation under certain circumstances. See my PR for a possible fix.
