### ISSUE TITLE
Fast click, drag, release can leave drag template open indefinitely

### ISSUE THREAD

**Issue by robbiehinch** [punker76/gong-wpf-dragdrop#504]
**Describe the bug**
Fast click, drag, release can leave drag template open indefinitely.
I've made a suggested fix in this PR: https://github.com/punker76/gong-wpf-dragdrop/pull/503

**To Reproduce**
Very quickly drag and drop a UI element (our application has a quite deeply nested grid layout that perhaps exacerbates the issue).

**Expected behavior**
The drag template will not disappear after releasing the drag.

**Desktop (please complete the following information):**
 - Windows 11

**Additional context**
I've made a suggested fix in this PR: https://github.com/punker76/gong-wpf-dragdrop/pull/503
There is a copy of the output logging I used to diagnose the issue.

**Comment by FAMEEXE** [comment]
Hi Robbie, do you get an exception before the template hung? We also had this bug, and we were able to fix this. :)

**Comment by robbiehinch** [comment]
> Hi Robbie, do you get an exception before the template hung? We also had this bug, and we were able to fix this. :)

I wasn't getting an exception. To me it seemed the issue is caused because the DragEnter event only bubbles into the ui element after the mouse has been released. Have you got a link to your fix/issue, please?

**Comment by FAMEEXE** [comment]
@robbiehinch we fixed this issue in #502 but the owner of this repo doesn't seem to be active anymore. So we fixed this issue in a fork with our own package: 
* Package: https://www.nuget.org/packages/softwaretirol.gong-wpf-dragdrop 
* Source: https://github.com/softwaretirol/gong-wpf-dragdrop/tree/ThreadingProblem

**Comment by punker76** [comment]
@FAMEEXE Sorry for delay, I'm active, but have currently some outer space human issues. I saw your PR and will look for it to merge it soon

**Comment by robbiehinch** [comment]
> May i ask, what version of .NET Framework/.NET are you using?

4.8 ftw

**Comment by punker76** [comment]
I think this is fixed by #497
