### ISSUE TITLE
Always Show DragAdorner While Dragging Regardless of Location

### ISSUE THREAD

**Issue by jstevenson72** [punker76/gong-wpf-dragdrop#58]
I saw this was a closed issue, but I haven't been able to get what I'm looking for in terms of the DragAdorner being showing while dragging from a Source to a Target.

The behavior I am looking for is the ability to start a Drag on a DragSource and immediately see the Adorner present.  And the Adorner would stay visible until drop or cancel the drag.

I need the item visible regardless of where on the screen I am dragging (whether it is a DropTarget or some other UI Element).

I would imaging I would define the DragAdornerTemplate on the source.

Something like this:

dd:DragDrop.DragAdornerTemplate="{StaticResource DragTemplateRing}"
dd:DragDrop.ForceAdornerVisibleWhileDragging="True"
dd:DragDrop.IsDragSource="True"

**Comment by krisrok** [comment]
+1

**Comment by krisrok** [comment]
pretty ok solution is to:
1. add `dnd:IsDropTarget="True"` to parent (e.g. Window or UserControl)
2. add `dnd:DragDrop.DropHandler="{Binding WindowDropHandler}"` (and be sure to deliver an instance via your DataContext)
3. implement WindowDropHandler to never handle anything:
```c#
public class WindowDropHandler : DefaultDropHandler
  {
    public override void DragOver(IDropInfo dropInfo)
    {
      dropInfo.NotHandled = true;
    }

    public override void Drop(IDropInfo dropInfo)
    {
      dropInfo.NotHandled = true;
    }
  }
```
4. adorner will be shown all the time

**Comment by punker76** [comment]
@jstevenson72 :wink: 

<a href='https://pledgie.com/campaigns/31030'><img alt='Click here to lend your support to: GongSolutions.WPF.DragDrop and make a donation at pledgie.com !' src='https://pledgie.com/campaigns/31030.png?skin_name=chrome' border='0' ></a>

**Comment by punker76** [comment]
@jstevenson72 I've added a sample to the demo to show this behavior with this custom DropHandler until a better solution is available...

```csharp
  public class ListBoxCustomDropHandler : DefaultDropHandler
  {
    public override void DragOver(IDropInfo dropInfo)
    {
      if (dropInfo.VisualTarget == dropInfo.DragInfo.VisualSource)
      {
        dropInfo.NotHandled = dropInfo.VisualTarget == dropInfo.DragInfo.VisualSource;
      }
      else
      {
        base.DragOver(dropInfo);
      }
    }

    public override void Drop(IDropInfo dropInfo)
    {
      if (dropInfo.VisualTarget == dropInfo.DragInfo.VisualSource)
      {
        dropInfo.NotHandled = dropInfo.VisualTarget == dropInfo.DragInfo.VisualSource;
      }
      else
      {
        base.Drop(dropInfo);
      }
    }
  }
```

Hope this is ok for you.
