### ISSUE TITLE
Problem with RelativeInsertPosition enum definition

### ISSUE THREAD

**Issue by akaztp** [punker76/gong-wpf-dragdrop#60]
Enumeration of RelativeInsertPosition on DropInfo.cs file should be set to powers of 2 since it is a Flags enumeration.
Now is:
    [Flags]
    public enum RelativeInsertPosition
    {
        BeforeTargetItem = 0,
        AfterTargetItem = 1,
        TargetItemCenter = 2
    }

which makes "bef" become true on:

RelativeInsertPosition pos = RelativeInsertPosition.AfterTargetItem;
bool bef = pos.HasFlag(RelativeInsertPosition.BeforeTargetItem);

On a local version of 0.1.3.6, I corrected the enumeration to:

    [Flags]
    public enum RelativeInsertPosition
    {
        BeforeTargetItem = 1,
        AfterTargetItem = 2,
        TargetItemCenter = 4
    }

And then it worked correctly.

**Comment by punker76** [comment]
@akaztp Should be fixed with 3b0995cfce9a38c70f8674773204dcb173fd20b4
