### ISSUE TITLE
Can't resize GridView and DataGrid columns

### ISSUE THREAD

**Issue by meroving** [punker76/gong-wpf-dragdrop#62]
First item of list become dragged when column separator is dragged by mouse in grid header. Width of column isn't changing.

**Comment by timeichfeld-msa** [comment]
Hello,  
This still does not seem to work, I cannot resize headers in a GridControl.
If I set dd:DragDrop.IsDragSource="False" in the Grid, I get resize of columns back, but can't drag/drop.
Is there a solution, or a flag I need to set or a special way to define the DD on the grid?

Please advise.

Thanks much! :)
