### ISSUE TITLE
Unable to cast object of type 'System.Windows.Documents.Run' to type 'System.Windows.Media.Visual'

### ISSUE THREAD

**Issue by bozalina** [punker76/gong-wpf-dragdrop#92]
Hey,

Looks like the code introduced in the fix for issue #84 casts e.OriginalSource to a Visual.  If the source is a Run, this cast throws an exception, since Runs aren't Visuals.

Thanks!

**Comment by msoyer34** [comment]
Hey, 

In the new version of gong solutions this occurs again. 

![image](https://user-images.githubusercontent.com/63670536/161230933-f1cf226d-be20-4511-96ac-53a60befe071.png)

I have tried to add try-catch method but exception is not from the MenuItem.

**Comment by punker76** [comment]
@msoyer34 Please open a new issue and provide a simple repo with exactly this issue or give more information about it with some code examples. Thx
