### ISSUE TITLE
Support for dragging a file in from outside the application?

### ISSUE THREAD

**Issue by erodewald** [punker76/gong-wpf-dragdrop#93]
For whatever reason, I can't get the Drop handler to execute, but DragOver works fine. I have looked through the project a bit but I don't see any mention of support for dragging something in from, say, the Windows file explorer. This is my primary need for drag & drop.

**Comment by lmuestak** [comment]
Hi @erodewald, Hi @punker76 

I have exactly the same problem. I described a possible bug here: #428. But there is also my ViewModel definition and the implementation of drag and drop. FolderBrowserViewModel contains a property called Items of type ObservableCollection<FolderViewModel> which represents a folder in the file system. I'm able to drag files and folders from windows explorer to my application (dragging files and folders from Windows Explorer to TreeView and ListView). But how can I drag TreeViewItems or ListViewItems from my application (TreeView/ListView) to Windows Explotrer to copy the underlying files and folders where I dropped them in Windows Explorer?

Any ideas?

Best regards
Leon
